-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity packetFormatter_hardcode_64 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    packetIn_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    packetIn_TVALID : IN STD_LOGIC;
    packetIn_TREADY : OUT STD_LOGIC;
    packetIn_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    packetIn_TDEST : IN STD_LOGIC_VECTOR (7 downto 0);
    packetIn_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    eth_dst_V : IN STD_LOGIC_VECTOR (47 downto 0);
    eth_src_V : IN STD_LOGIC_VECTOR (47 downto 0);
    packetOut_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    packetOut_TVALID : OUT STD_LOGIC;
    packetOut_TREADY : IN STD_LOGIC;
    packetOut_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    packetOut_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of packetFormatter_hardcode_64 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "packetFormatter_hardcode_64,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku115-flva1517-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.835000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=467,HLS_SYN_LUT=388}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv16_7400 : STD_LOGIC_VECTOR (15 downto 0) := "0111010000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal packetIn_V_data_V_0_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal packetIn_V_data_V_0_vld_in : STD_LOGIC;
    signal packetIn_V_data_V_0_vld_out : STD_LOGIC;
    signal packetIn_V_data_V_0_ack_in : STD_LOGIC;
    signal packetIn_V_data_V_0_ack_out : STD_LOGIC;
    signal packetIn_V_data_V_0_payload_A : STD_LOGIC_VECTOR (63 downto 0);
    signal packetIn_V_data_V_0_payload_B : STD_LOGIC_VECTOR (63 downto 0);
    signal packetIn_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal packetIn_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal packetIn_V_data_V_0_sel : STD_LOGIC;
    signal packetIn_V_data_V_0_load_A : STD_LOGIC;
    signal packetIn_V_data_V_0_load_B : STD_LOGIC;
    signal packetIn_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetIn_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal packetIn_V_last_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal packetIn_V_last_V_0_vld_in : STD_LOGIC;
    signal packetIn_V_last_V_0_vld_out : STD_LOGIC;
    signal packetIn_V_last_V_0_ack_in : STD_LOGIC;
    signal packetIn_V_last_V_0_ack_out : STD_LOGIC;
    signal packetIn_V_last_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal packetIn_V_last_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal packetIn_V_last_V_0_sel_rd : STD_LOGIC := '0';
    signal packetIn_V_last_V_0_sel_wr : STD_LOGIC := '0';
    signal packetIn_V_last_V_0_sel : STD_LOGIC;
    signal packetIn_V_last_V_0_load_A : STD_LOGIC;
    signal packetIn_V_last_V_0_load_B : STD_LOGIC;
    signal packetIn_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetIn_V_last_V_0_state_cmp_full : STD_LOGIC;
    signal packetIn_V_dest_V_0_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal packetIn_V_dest_V_0_vld_in : STD_LOGIC;
    signal packetIn_V_dest_V_0_vld_out : STD_LOGIC;
    signal packetIn_V_dest_V_0_ack_in : STD_LOGIC;
    signal packetIn_V_dest_V_0_ack_out : STD_LOGIC;
    signal packetIn_V_dest_V_0_payload_A : STD_LOGIC_VECTOR (7 downto 0);
    signal packetIn_V_dest_V_0_payload_B : STD_LOGIC_VECTOR (7 downto 0);
    signal packetIn_V_dest_V_0_sel_rd : STD_LOGIC := '0';
    signal packetIn_V_dest_V_0_sel_wr : STD_LOGIC := '0';
    signal packetIn_V_dest_V_0_sel : STD_LOGIC;
    signal packetIn_V_dest_V_0_load_A : STD_LOGIC;
    signal packetIn_V_dest_V_0_load_B : STD_LOGIC;
    signal packetIn_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetIn_V_dest_V_0_state_cmp_full : STD_LOGIC;
    signal packetIn_V_keep_V_0_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal packetIn_V_keep_V_0_vld_in : STD_LOGIC;
    signal packetIn_V_keep_V_0_vld_out : STD_LOGIC;
    signal packetIn_V_keep_V_0_ack_in : STD_LOGIC;
    signal packetIn_V_keep_V_0_ack_out : STD_LOGIC;
    signal packetIn_V_keep_V_0_payload_A : STD_LOGIC_VECTOR (7 downto 0);
    signal packetIn_V_keep_V_0_payload_B : STD_LOGIC_VECTOR (7 downto 0);
    signal packetIn_V_keep_V_0_sel_rd : STD_LOGIC := '0';
    signal packetIn_V_keep_V_0_sel_wr : STD_LOGIC := '0';
    signal packetIn_V_keep_V_0_sel : STD_LOGIC;
    signal packetIn_V_keep_V_0_load_A : STD_LOGIC;
    signal packetIn_V_keep_V_0_load_B : STD_LOGIC;
    signal packetIn_V_keep_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetIn_V_keep_V_0_state_cmp_full : STD_LOGIC;
    signal packetOut_V_data_V_1_data_in : STD_LOGIC_VECTOR (63 downto 0);
    signal packetOut_V_data_V_1_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal packetOut_V_data_V_1_vld_in : STD_LOGIC;
    signal packetOut_V_data_V_1_vld_out : STD_LOGIC;
    signal packetOut_V_data_V_1_ack_in : STD_LOGIC;
    signal packetOut_V_data_V_1_ack_out : STD_LOGIC;
    signal packetOut_V_data_V_1_payload_A : STD_LOGIC_VECTOR (63 downto 0);
    signal packetOut_V_data_V_1_payload_B : STD_LOGIC_VECTOR (63 downto 0);
    signal packetOut_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal packetOut_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal packetOut_V_data_V_1_sel : STD_LOGIC;
    signal packetOut_V_data_V_1_load_A : STD_LOGIC;
    signal packetOut_V_data_V_1_load_B : STD_LOGIC;
    signal packetOut_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetOut_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal packetOut_V_last_V_1_data_in : STD_LOGIC_VECTOR (0 downto 0);
    signal packetOut_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal packetOut_V_last_V_1_vld_in : STD_LOGIC;
    signal packetOut_V_last_V_1_vld_out : STD_LOGIC;
    signal packetOut_V_last_V_1_ack_in : STD_LOGIC;
    signal packetOut_V_last_V_1_ack_out : STD_LOGIC;
    signal packetOut_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal packetOut_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal packetOut_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal packetOut_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal packetOut_V_last_V_1_sel : STD_LOGIC;
    signal packetOut_V_last_V_1_load_A : STD_LOGIC;
    signal packetOut_V_last_V_1_load_B : STD_LOGIC;
    signal packetOut_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetOut_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal packetOut_V_keep_V_1_data_in : STD_LOGIC_VECTOR (7 downto 0);
    signal packetOut_V_keep_V_1_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal packetOut_V_keep_V_1_vld_in : STD_LOGIC;
    signal packetOut_V_keep_V_1_vld_out : STD_LOGIC;
    signal packetOut_V_keep_V_1_ack_in : STD_LOGIC;
    signal packetOut_V_keep_V_1_ack_out : STD_LOGIC;
    signal packetOut_V_keep_V_1_payload_A : STD_LOGIC_VECTOR (7 downto 0);
    signal packetOut_V_keep_V_1_payload_B : STD_LOGIC_VECTOR (7 downto 0);
    signal packetOut_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal packetOut_V_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal packetOut_V_keep_V_1_sel : STD_LOGIC;
    signal packetOut_V_keep_V_1_load_A : STD_LOGIC;
    signal packetOut_V_keep_V_1_load_B : STD_LOGIC;
    signal packetOut_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal packetOut_V_keep_V_1_state_cmp_full : STD_LOGIC;
    signal packetIn_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal packetOut_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal reg_124 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_reg_175 : STD_LOGIC_VECTOR (15 downto 0);
    signal temp_V_fu_139_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_V_reg_180 : STD_LOGIC_VECTOR (31 downto 0);
    signal packetHeader0_data_V_fu_143_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_last_V_reg_190 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_154_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_last_V_1_reg_206 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_p_s_phi_fu_108_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_reg_105 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_state6 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    packetIn_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((packetIn_V_data_V_0_ack_out = ap_const_logic_1) and (packetIn_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        packetIn_V_data_V_0_sel_rd <= not(packetIn_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((packetIn_V_data_V_0_ack_in = ap_const_logic_1) and (packetIn_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        packetIn_V_data_V_0_sel_wr <= not(packetIn_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((packetIn_V_data_V_0_state = ap_const_lv2_2) and (packetIn_V_data_V_0_vld_in = ap_const_logic_0)) or ((packetIn_V_data_V_0_state = ap_const_lv2_3) and (packetIn_V_data_V_0_vld_in = ap_const_logic_0) and (packetIn_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    packetIn_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((packetIn_V_data_V_0_state = ap_const_lv2_1) and (packetIn_V_data_V_0_ack_out = ap_const_logic_0)) or ((packetIn_V_data_V_0_state = ap_const_lv2_3) and (packetIn_V_data_V_0_ack_out = ap_const_logic_0) and (packetIn_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((packetIn_V_data_V_0_vld_in = ap_const_logic_0) and (packetIn_V_data_V_0_ack_out = ap_const_logic_1))) and not(((packetIn_V_data_V_0_ack_out = ap_const_logic_0) and (packetIn_V_data_V_0_vld_in = ap_const_logic_1))) and (packetIn_V_data_V_0_state = ap_const_lv2_3)) or ((packetIn_V_data_V_0_state = ap_const_lv2_1) and (packetIn_V_data_V_0_ack_out = ap_const_logic_1)) or ((packetIn_V_data_V_0_state = ap_const_lv2_2) and (packetIn_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    packetIn_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_dest_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_dest_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((packetIn_V_dest_V_0_ack_out = ap_const_logic_1) and (packetIn_V_dest_V_0_vld_out = ap_const_logic_1))) then 
                                        packetIn_V_dest_V_0_sel_rd <= not(packetIn_V_dest_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_dest_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_dest_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((packetIn_V_dest_V_0_ack_in = ap_const_logic_1) and (packetIn_V_dest_V_0_vld_in = ap_const_logic_1))) then 
                                        packetIn_V_dest_V_0_sel_wr <= not(packetIn_V_dest_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((packetIn_V_dest_V_0_state = ap_const_lv2_2) and (packetIn_V_dest_V_0_vld_in = ap_const_logic_0)) or ((packetIn_V_dest_V_0_state = ap_const_lv2_3) and (packetIn_V_dest_V_0_vld_in = ap_const_logic_0) and (packetIn_V_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    packetIn_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((packetIn_V_dest_V_0_state = ap_const_lv2_1) and (packetIn_V_dest_V_0_ack_out = ap_const_logic_0)) or ((packetIn_V_dest_V_0_state = ap_const_lv2_3) and (packetIn_V_dest_V_0_ack_out = ap_const_logic_0) and (packetIn_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((packetIn_V_dest_V_0_vld_in = ap_const_logic_0) and (packetIn_V_dest_V_0_ack_out = ap_const_logic_1))) and not(((packetIn_V_dest_V_0_ack_out = ap_const_logic_0) and (packetIn_V_dest_V_0_vld_in = ap_const_logic_1))) and (packetIn_V_dest_V_0_state = ap_const_lv2_3)) or ((packetIn_V_dest_V_0_state = ap_const_lv2_1) and (packetIn_V_dest_V_0_ack_out = ap_const_logic_1)) or ((packetIn_V_dest_V_0_state = ap_const_lv2_2) and (packetIn_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    packetIn_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_keep_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_keep_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((packetIn_V_keep_V_0_ack_out = ap_const_logic_1) and (packetIn_V_keep_V_0_vld_out = ap_const_logic_1))) then 
                                        packetIn_V_keep_V_0_sel_rd <= not(packetIn_V_keep_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_keep_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_keep_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((packetIn_V_keep_V_0_ack_in = ap_const_logic_1) and (packetIn_V_keep_V_0_vld_in = ap_const_logic_1))) then 
                                        packetIn_V_keep_V_0_sel_wr <= not(packetIn_V_keep_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_keep_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_keep_V_0_state <= ap_const_lv2_0;
            else
                if ((((packetIn_V_keep_V_0_state = ap_const_lv2_2) and (packetIn_V_keep_V_0_vld_in = ap_const_logic_0)) or ((packetIn_V_keep_V_0_state = ap_const_lv2_3) and (packetIn_V_keep_V_0_vld_in = ap_const_logic_0) and (packetIn_V_keep_V_0_ack_out = ap_const_logic_1)))) then 
                    packetIn_V_keep_V_0_state <= ap_const_lv2_2;
                elsif ((((packetIn_V_keep_V_0_state = ap_const_lv2_1) and (packetIn_V_keep_V_0_ack_out = ap_const_logic_0)) or ((packetIn_V_keep_V_0_state = ap_const_lv2_3) and (packetIn_V_keep_V_0_ack_out = ap_const_logic_0) and (packetIn_V_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_keep_V_0_state <= ap_const_lv2_1;
                elsif (((not(((packetIn_V_keep_V_0_vld_in = ap_const_logic_0) and (packetIn_V_keep_V_0_ack_out = ap_const_logic_1))) and not(((packetIn_V_keep_V_0_ack_out = ap_const_logic_0) and (packetIn_V_keep_V_0_vld_in = ap_const_logic_1))) and (packetIn_V_keep_V_0_state = ap_const_lv2_3)) or ((packetIn_V_keep_V_0_state = ap_const_lv2_1) and (packetIn_V_keep_V_0_ack_out = ap_const_logic_1)) or ((packetIn_V_keep_V_0_state = ap_const_lv2_2) and (packetIn_V_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_keep_V_0_state <= ap_const_lv2_3;
                else 
                    packetIn_V_keep_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_last_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_last_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((packetIn_V_last_V_0_ack_out = ap_const_logic_1) and (packetIn_V_last_V_0_vld_out = ap_const_logic_1))) then 
                                        packetIn_V_last_V_0_sel_rd <= not(packetIn_V_last_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_last_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_last_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((packetIn_V_last_V_0_ack_in = ap_const_logic_1) and (packetIn_V_last_V_0_vld_in = ap_const_logic_1))) then 
                                        packetIn_V_last_V_0_sel_wr <= not(packetIn_V_last_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetIn_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetIn_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((packetIn_V_last_V_0_state = ap_const_lv2_2) and (packetIn_V_last_V_0_vld_in = ap_const_logic_0)) or ((packetIn_V_last_V_0_state = ap_const_lv2_3) and (packetIn_V_last_V_0_vld_in = ap_const_logic_0) and (packetIn_V_last_V_0_ack_out = ap_const_logic_1)))) then 
                    packetIn_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((packetIn_V_last_V_0_state = ap_const_lv2_1) and (packetIn_V_last_V_0_ack_out = ap_const_logic_0)) or ((packetIn_V_last_V_0_state = ap_const_lv2_3) and (packetIn_V_last_V_0_ack_out = ap_const_logic_0) and (packetIn_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((packetIn_V_last_V_0_vld_in = ap_const_logic_0) and (packetIn_V_last_V_0_ack_out = ap_const_logic_1))) and not(((packetIn_V_last_V_0_ack_out = ap_const_logic_0) and (packetIn_V_last_V_0_vld_in = ap_const_logic_1))) and (packetIn_V_last_V_0_state = ap_const_lv2_3)) or ((packetIn_V_last_V_0_state = ap_const_lv2_1) and (packetIn_V_last_V_0_ack_out = ap_const_logic_1)) or ((packetIn_V_last_V_0_state = ap_const_lv2_2) and (packetIn_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    packetIn_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    packetIn_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((packetOut_V_data_V_1_ack_out = ap_const_logic_1) and (packetOut_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        packetOut_V_data_V_1_sel_rd <= not(packetOut_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (packetOut_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        packetOut_V_data_V_1_sel_wr <= not(packetOut_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((packetOut_V_data_V_1_state = ap_const_lv2_2) and (packetOut_V_data_V_1_vld_in = ap_const_logic_0)) or ((packetOut_V_data_V_1_state = ap_const_lv2_3) and (packetOut_V_data_V_1_vld_in = ap_const_logic_0) and (packetOut_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    packetOut_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((packetOut_V_data_V_1_state = ap_const_lv2_1) and (packetOut_V_data_V_1_ack_out = ap_const_logic_0)) or ((packetOut_V_data_V_1_state = ap_const_lv2_3) and (packetOut_V_data_V_1_ack_out = ap_const_logic_0) and (packetOut_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    packetOut_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((packetOut_V_data_V_1_vld_in = ap_const_logic_0) and (packetOut_V_data_V_1_ack_out = ap_const_logic_1))) and not(((packetOut_V_data_V_1_ack_out = ap_const_logic_0) and (packetOut_V_data_V_1_vld_in = ap_const_logic_1))) and (packetOut_V_data_V_1_state = ap_const_lv2_3)) or ((packetOut_V_data_V_1_state = ap_const_lv2_1) and (packetOut_V_data_V_1_ack_out = ap_const_logic_1)) or ((packetOut_V_data_V_1_state = ap_const_lv2_2) and (packetOut_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    packetOut_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    packetOut_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((packetOut_V_keep_V_1_ack_out = ap_const_logic_1) and (packetOut_V_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        packetOut_V_keep_V_1_sel_rd <= not(packetOut_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((packetOut_V_keep_V_1_ack_in = ap_const_logic_1) and (packetOut_V_keep_V_1_vld_in = ap_const_logic_1))) then 
                                        packetOut_V_keep_V_1_sel_wr <= not(packetOut_V_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((packetOut_V_keep_V_1_state = ap_const_lv2_2) and (packetOut_V_keep_V_1_vld_in = ap_const_logic_0)) or ((packetOut_V_keep_V_1_state = ap_const_lv2_3) and (packetOut_V_keep_V_1_vld_in = ap_const_logic_0) and (packetOut_V_keep_V_1_ack_out = ap_const_logic_1)))) then 
                    packetOut_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((packetOut_V_keep_V_1_state = ap_const_lv2_1) and (packetOut_V_keep_V_1_ack_out = ap_const_logic_0)) or ((packetOut_V_keep_V_1_state = ap_const_lv2_3) and (packetOut_V_keep_V_1_ack_out = ap_const_logic_0) and (packetOut_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    packetOut_V_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((packetOut_V_keep_V_1_vld_in = ap_const_logic_0) and (packetOut_V_keep_V_1_ack_out = ap_const_logic_1))) and not(((packetOut_V_keep_V_1_ack_out = ap_const_logic_0) and (packetOut_V_keep_V_1_vld_in = ap_const_logic_1))) and (packetOut_V_keep_V_1_state = ap_const_lv2_3)) or ((packetOut_V_keep_V_1_state = ap_const_lv2_1) and (packetOut_V_keep_V_1_ack_out = ap_const_logic_1)) or ((packetOut_V_keep_V_1_state = ap_const_lv2_2) and (packetOut_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    packetOut_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    packetOut_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((packetOut_V_last_V_1_ack_out = ap_const_logic_1) and (packetOut_V_last_V_1_vld_out = ap_const_logic_1))) then 
                                        packetOut_V_last_V_1_sel_rd <= not(packetOut_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((packetOut_V_last_V_1_ack_in = ap_const_logic_1) and (packetOut_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        packetOut_V_last_V_1_sel_wr <= not(packetOut_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    packetOut_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                packetOut_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((packetOut_V_last_V_1_state = ap_const_lv2_2) and (packetOut_V_last_V_1_vld_in = ap_const_logic_0)) or ((packetOut_V_last_V_1_state = ap_const_lv2_3) and (packetOut_V_last_V_1_vld_in = ap_const_logic_0) and (packetOut_V_last_V_1_ack_out = ap_const_logic_1)))) then 
                    packetOut_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((packetOut_V_last_V_1_state = ap_const_lv2_1) and (packetOut_V_last_V_1_ack_out = ap_const_logic_0)) or ((packetOut_V_last_V_1_state = ap_const_lv2_3) and (packetOut_V_last_V_1_ack_out = ap_const_logic_0) and (packetOut_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    packetOut_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((packetOut_V_last_V_1_vld_in = ap_const_logic_0) and (packetOut_V_last_V_1_ack_out = ap_const_logic_1))) and not(((packetOut_V_last_V_1_ack_out = ap_const_logic_0) and (packetOut_V_last_V_1_vld_in = ap_const_logic_1))) and (packetOut_V_last_V_1_state = ap_const_lv2_3)) or ((packetOut_V_last_V_1_state = ap_const_lv2_1) and (packetOut_V_last_V_1_ack_out = ap_const_logic_1)) or ((packetOut_V_last_V_1_state = ap_const_lv2_2) and (packetOut_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    packetOut_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    packetOut_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    p_s_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_data_V_1_ack_in = ap_const_logic_1)) then
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    p_s_reg_105 <= tmp_last_V_1_reg_206;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    p_s_reg_105 <= tmp_last_V_reg_190;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_data_V_0_load_A = ap_const_logic_1)) then
                packetIn_V_data_V_0_payload_A <= packetIn_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_data_V_0_load_B = ap_const_logic_1)) then
                packetIn_V_data_V_0_payload_B <= packetIn_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_dest_V_0_load_A = ap_const_logic_1)) then
                packetIn_V_dest_V_0_payload_A <= packetIn_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_dest_V_0_load_B = ap_const_logic_1)) then
                packetIn_V_dest_V_0_payload_B <= packetIn_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_keep_V_0_load_A = ap_const_logic_1)) then
                packetIn_V_keep_V_0_payload_A <= packetIn_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_keep_V_0_load_B = ap_const_logic_1)) then
                packetIn_V_keep_V_0_payload_B <= packetIn_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_last_V_0_load_A = ap_const_logic_1)) then
                packetIn_V_last_V_0_payload_A <= packetIn_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetIn_V_last_V_0_load_B = ap_const_logic_1)) then
                packetIn_V_last_V_0_payload_B <= packetIn_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_data_V_1_load_A = ap_const_logic_1)) then
                packetOut_V_data_V_1_payload_A <= packetOut_V_data_V_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_data_V_1_load_B = ap_const_logic_1)) then
                packetOut_V_data_V_1_payload_B <= packetOut_V_data_V_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_keep_V_1_load_A = ap_const_logic_1)) then
                packetOut_V_keep_V_1_payload_A <= packetOut_V_keep_V_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_keep_V_1_load_B = ap_const_logic_1)) then
                packetOut_V_keep_V_1_payload_B <= packetOut_V_keep_V_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_last_V_1_load_A = ap_const_logic_1)) then
                packetOut_V_last_V_1_payload_A <= packetOut_V_last_V_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((packetOut_V_last_V_1_load_B = ap_const_logic_1)) then
                packetOut_V_last_V_1_payload_B <= packetOut_V_last_V_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then
                reg_124 <= packetIn_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                temp_V_reg_180 <= temp_V_fu_139_p1;
                tmp_reg_175 <= eth_src_V(47 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_dest_V_reg_196 <= packetIn_V_dest_V_0_data_out;
                tmp_last_V_reg_190 <= packetIn_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                tmp_last_V_1_reg_206 <= packetIn_V_last_V_0_data_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, packetOut_V_last_V_1_ack_in, packetOut_V_keep_V_1_ack_in, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_phi_mux_p_s_phi_fu_108_p4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if ((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((packetOut_V_keep_V_1_ack_in = ap_const_logic_0) or (packetOut_V_last_V_1_ack_in = ap_const_logic_0) or (packetOut_V_data_V_1_ack_in = ap_const_logic_0))) and (ap_phi_mux_p_s_phi_fu_108_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((packetOut_V_keep_V_1_ack_in = ap_const_logic_0) or (packetOut_V_last_V_1_ack_in = ap_const_logic_0) or (packetOut_V_data_V_1_ack_in = ap_const_logic_0))) and (ap_phi_mux_p_s_phi_fu_108_p4 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_block_state6_assign_proc : process(packetOut_V_data_V_1_ack_in, packetOut_V_last_V_1_ack_in, packetOut_V_keep_V_1_ack_in)
    begin
                ap_block_state6 <= ((packetOut_V_keep_V_1_ack_in = ap_const_logic_0) or (packetOut_V_last_V_1_ack_in = ap_const_logic_0) or (packetOut_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

    ap_phi_mux_p_s_phi_fu_108_p4 <= p_s_reg_105;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    p_Result_s_fu_154_p5 <= (((temp_V_reg_180 & ap_const_lv16_7400) & tmp_dest_V_reg_196) & ap_const_lv8_0);
    packetHeader0_data_V_fu_143_p3 <= (eth_dst_V & tmp_reg_175);

    packetIn_TDATA_blk_n_assign_proc : process(packetIn_V_data_V_0_state, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            packetIn_TDATA_blk_n <= packetIn_V_data_V_0_state(0);
        else 
            packetIn_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    packetIn_TREADY <= packetIn_V_keep_V_0_state(1);
    packetIn_V_data_V_0_ack_in <= packetIn_V_data_V_0_state(1);

    packetIn_V_data_V_0_ack_out_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetIn_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            packetIn_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    packetIn_V_data_V_0_data_out_assign_proc : process(packetIn_V_data_V_0_payload_A, packetIn_V_data_V_0_payload_B, packetIn_V_data_V_0_sel)
    begin
        if ((packetIn_V_data_V_0_sel = ap_const_logic_1)) then 
            packetIn_V_data_V_0_data_out <= packetIn_V_data_V_0_payload_B;
        else 
            packetIn_V_data_V_0_data_out <= packetIn_V_data_V_0_payload_A;
        end if; 
    end process;

    packetIn_V_data_V_0_load_A <= (packetIn_V_data_V_0_state_cmp_full and not(packetIn_V_data_V_0_sel_wr));
    packetIn_V_data_V_0_load_B <= (packetIn_V_data_V_0_state_cmp_full and packetIn_V_data_V_0_sel_wr);
    packetIn_V_data_V_0_sel <= packetIn_V_data_V_0_sel_rd;
    packetIn_V_data_V_0_state_cmp_full <= '0' when (packetIn_V_data_V_0_state = ap_const_lv2_1) else '1';
    packetIn_V_data_V_0_vld_in <= packetIn_TVALID;
    packetIn_V_data_V_0_vld_out <= packetIn_V_data_V_0_state(0);
    packetIn_V_dest_V_0_ack_in <= packetIn_V_dest_V_0_state(1);

    packetIn_V_dest_V_0_ack_out_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetIn_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            packetIn_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    packetIn_V_dest_V_0_data_out_assign_proc : process(packetIn_V_dest_V_0_payload_A, packetIn_V_dest_V_0_payload_B, packetIn_V_dest_V_0_sel)
    begin
        if ((packetIn_V_dest_V_0_sel = ap_const_logic_1)) then 
            packetIn_V_dest_V_0_data_out <= packetIn_V_dest_V_0_payload_B;
        else 
            packetIn_V_dest_V_0_data_out <= packetIn_V_dest_V_0_payload_A;
        end if; 
    end process;

    packetIn_V_dest_V_0_load_A <= (packetIn_V_dest_V_0_state_cmp_full and not(packetIn_V_dest_V_0_sel_wr));
    packetIn_V_dest_V_0_load_B <= (packetIn_V_dest_V_0_state_cmp_full and packetIn_V_dest_V_0_sel_wr);
    packetIn_V_dest_V_0_sel <= packetIn_V_dest_V_0_sel_rd;
    packetIn_V_dest_V_0_state_cmp_full <= '0' when (packetIn_V_dest_V_0_state = ap_const_lv2_1) else '1';
    packetIn_V_dest_V_0_vld_in <= packetIn_TVALID;
    packetIn_V_dest_V_0_vld_out <= packetIn_V_dest_V_0_state(0);
    packetIn_V_keep_V_0_ack_in <= packetIn_V_keep_V_0_state(1);

    packetIn_V_keep_V_0_ack_out_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetIn_V_keep_V_0_ack_out <= ap_const_logic_1;
        else 
            packetIn_V_keep_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    packetIn_V_keep_V_0_data_out_assign_proc : process(packetIn_V_keep_V_0_payload_A, packetIn_V_keep_V_0_payload_B, packetIn_V_keep_V_0_sel)
    begin
        if ((packetIn_V_keep_V_0_sel = ap_const_logic_1)) then 
            packetIn_V_keep_V_0_data_out <= packetIn_V_keep_V_0_payload_B;
        else 
            packetIn_V_keep_V_0_data_out <= packetIn_V_keep_V_0_payload_A;
        end if; 
    end process;

    packetIn_V_keep_V_0_load_A <= (packetIn_V_keep_V_0_state_cmp_full and not(packetIn_V_keep_V_0_sel_wr));
    packetIn_V_keep_V_0_load_B <= (packetIn_V_keep_V_0_state_cmp_full and packetIn_V_keep_V_0_sel_wr);
    packetIn_V_keep_V_0_sel <= packetIn_V_keep_V_0_sel_rd;
    packetIn_V_keep_V_0_state_cmp_full <= '0' when (packetIn_V_keep_V_0_state = ap_const_lv2_1) else '1';
    packetIn_V_keep_V_0_vld_in <= packetIn_TVALID;
    packetIn_V_keep_V_0_vld_out <= packetIn_V_keep_V_0_state(0);
    packetIn_V_last_V_0_ack_in <= packetIn_V_last_V_0_state(1);

    packetIn_V_last_V_0_ack_out_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7)
    begin
        if (((not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetIn_V_last_V_0_ack_out <= ap_const_logic_1;
        else 
            packetIn_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    packetIn_V_last_V_0_data_out_assign_proc : process(packetIn_V_last_V_0_payload_A, packetIn_V_last_V_0_payload_B, packetIn_V_last_V_0_sel)
    begin
        if ((packetIn_V_last_V_0_sel = ap_const_logic_1)) then 
            packetIn_V_last_V_0_data_out <= packetIn_V_last_V_0_payload_B;
        else 
            packetIn_V_last_V_0_data_out <= packetIn_V_last_V_0_payload_A;
        end if; 
    end process;

    packetIn_V_last_V_0_load_A <= (packetIn_V_last_V_0_state_cmp_full and not(packetIn_V_last_V_0_sel_wr));
    packetIn_V_last_V_0_load_B <= (packetIn_V_last_V_0_state_cmp_full and packetIn_V_last_V_0_sel_wr);
    packetIn_V_last_V_0_sel <= packetIn_V_last_V_0_sel_rd;
    packetIn_V_last_V_0_state_cmp_full <= '0' when (packetIn_V_last_V_0_state = ap_const_lv2_1) else '1';
    packetIn_V_last_V_0_vld_in <= packetIn_TVALID;
    packetIn_V_last_V_0_vld_out <= packetIn_V_last_V_0_state(0);
    packetOut_TDATA <= packetOut_V_data_V_1_data_out;

    packetOut_TDATA_blk_n_assign_proc : process(packetOut_V_data_V_1_state, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            packetOut_TDATA_blk_n <= packetOut_V_data_V_1_state(1);
        else 
            packetOut_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    packetOut_TKEEP <= packetOut_V_keep_V_1_data_out;
    packetOut_TLAST <= packetOut_V_last_V_1_data_out;
    packetOut_TVALID <= packetOut_V_keep_V_1_state(0);
    packetOut_V_data_V_1_ack_in <= packetOut_V_data_V_1_state(1);
    packetOut_V_data_V_1_ack_out <= packetOut_TREADY;

    packetOut_V_data_V_1_data_in_assign_proc : process(packetIn_V_data_V_0_data_out, packetIn_V_data_V_0_vld_out, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4, reg_124, packetHeader0_data_V_fu_143_p3, p_Result_s_fu_154_p5)
    begin
        if (((packetIn_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            packetOut_V_data_V_1_data_in <= packetIn_V_data_V_0_data_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            packetOut_V_data_V_1_data_in <= reg_124;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            packetOut_V_data_V_1_data_in <= p_Result_s_fu_154_p5;
        elsif (((packetIn_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            packetOut_V_data_V_1_data_in <= packetHeader0_data_V_fu_143_p3;
        else 
            packetOut_V_data_V_1_data_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    packetOut_V_data_V_1_data_out_assign_proc : process(packetOut_V_data_V_1_payload_A, packetOut_V_data_V_1_payload_B, packetOut_V_data_V_1_sel)
    begin
        if ((packetOut_V_data_V_1_sel = ap_const_logic_1)) then 
            packetOut_V_data_V_1_data_out <= packetOut_V_data_V_1_payload_B;
        else 
            packetOut_V_data_V_1_data_out <= packetOut_V_data_V_1_payload_A;
        end if; 
    end process;

    packetOut_V_data_V_1_load_A <= (packetOut_V_data_V_1_state_cmp_full and not(packetOut_V_data_V_1_sel_wr));
    packetOut_V_data_V_1_load_B <= (packetOut_V_data_V_1_state_cmp_full and packetOut_V_data_V_1_sel_wr);
    packetOut_V_data_V_1_sel <= packetOut_V_data_V_1_sel_rd;
    packetOut_V_data_V_1_state_cmp_full <= '0' when (packetOut_V_data_V_1_state = ap_const_lv2_1) else '1';

    packetOut_V_data_V_1_vld_in_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetOut_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            packetOut_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    packetOut_V_data_V_1_vld_out <= packetOut_V_data_V_1_state(0);
    packetOut_V_keep_V_1_ack_in <= packetOut_V_keep_V_1_state(1);
    packetOut_V_keep_V_1_ack_out <= packetOut_TREADY;

    packetOut_V_keep_V_1_data_in_assign_proc : process(packetIn_V_data_V_0_vld_out, packetIn_V_keep_V_0_data_out, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((packetIn_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            packetOut_V_keep_V_1_data_in <= packetIn_V_keep_V_0_data_out;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((packetIn_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetOut_V_keep_V_1_data_in <= ap_const_lv8_FF;
        else 
            packetOut_V_keep_V_1_data_in <= "XXXXXXXX";
        end if; 
    end process;


    packetOut_V_keep_V_1_data_out_assign_proc : process(packetOut_V_keep_V_1_payload_A, packetOut_V_keep_V_1_payload_B, packetOut_V_keep_V_1_sel)
    begin
        if ((packetOut_V_keep_V_1_sel = ap_const_logic_1)) then 
            packetOut_V_keep_V_1_data_out <= packetOut_V_keep_V_1_payload_B;
        else 
            packetOut_V_keep_V_1_data_out <= packetOut_V_keep_V_1_payload_A;
        end if; 
    end process;

    packetOut_V_keep_V_1_load_A <= (packetOut_V_keep_V_1_state_cmp_full and not(packetOut_V_keep_V_1_sel_wr));
    packetOut_V_keep_V_1_load_B <= (packetOut_V_keep_V_1_state_cmp_full and packetOut_V_keep_V_1_sel_wr);
    packetOut_V_keep_V_1_sel <= packetOut_V_keep_V_1_sel_rd;
    packetOut_V_keep_V_1_state_cmp_full <= '0' when (packetOut_V_keep_V_1_state = ap_const_lv2_1) else '1';

    packetOut_V_keep_V_1_vld_in_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetOut_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            packetOut_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    packetOut_V_keep_V_1_vld_out <= packetOut_V_keep_V_1_state(0);
    packetOut_V_last_V_1_ack_in <= packetOut_V_last_V_1_state(1);
    packetOut_V_last_V_1_ack_out <= packetOut_TREADY;

    packetOut_V_last_V_1_data_in_assign_proc : process(packetIn_V_data_V_0_vld_out, packetIn_V_last_V_0_data_out, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4, tmp_last_V_reg_190)
    begin
        if (((packetIn_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            packetOut_V_last_V_1_data_in <= packetIn_V_last_V_0_data_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            packetOut_V_last_V_1_data_in <= tmp_last_V_reg_190;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((packetIn_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetOut_V_last_V_1_data_in <= ap_const_lv1_0;
        else 
            packetOut_V_last_V_1_data_in <= "X";
        end if; 
    end process;


    packetOut_V_last_V_1_data_out_assign_proc : process(packetOut_V_last_V_1_payload_A, packetOut_V_last_V_1_payload_B, packetOut_V_last_V_1_sel)
    begin
        if ((packetOut_V_last_V_1_sel = ap_const_logic_1)) then 
            packetOut_V_last_V_1_data_out <= packetOut_V_last_V_1_payload_B;
        else 
            packetOut_V_last_V_1_data_out <= packetOut_V_last_V_1_payload_A;
        end if; 
    end process;

    packetOut_V_last_V_1_load_A <= (packetOut_V_last_V_1_state_cmp_full and not(packetOut_V_last_V_1_sel_wr));
    packetOut_V_last_V_1_load_B <= (packetOut_V_last_V_1_state_cmp_full and packetOut_V_last_V_1_sel_wr);
    packetOut_V_last_V_1_sel <= packetOut_V_last_V_1_sel_rd;
    packetOut_V_last_V_1_state_cmp_full <= '0' when (packetOut_V_last_V_1_state = ap_const_lv2_1) else '1';

    packetOut_V_last_V_1_vld_in_assign_proc : process(packetIn_V_data_V_0_vld_out, packetOut_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((packetOut_V_data_V_1_ack_in = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((packetOut_V_data_V_1_ack_in = ap_const_logic_0) or (packetIn_V_data_V_0_vld_out = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            packetOut_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            packetOut_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    packetOut_V_last_V_1_vld_out <= packetOut_V_last_V_1_state(0);
    temp_V_fu_139_p1 <= eth_src_V(32 - 1 downto 0);
end behav;
