-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity NFR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    stream_in_V_dout : IN STD_LOGIC_VECTOR (80 downto 0);
    stream_in_V_empty_n : IN STD_LOGIC;
    stream_in_V_read : OUT STD_LOGIC;
    stream_out_V_din : OUT STD_LOGIC_VECTOR (128 downto 0);
    stream_out_V_full_n : IN STD_LOGIC;
    stream_out_V_write : OUT STD_LOGIC );
end;


architecture behav of NFR is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "NFR,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku115-flva1517-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.539000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=280,HLS_SYN_LUT=864}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv36_1 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv36_0 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv32_49 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001001";
    constant ap_const_lv32_4A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001010";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_FFFFFFF8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111000";

    signal stream_in_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_9_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_nbreadreq_fu_187_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal stream_out_V_blk_n : STD_LOGIC;
    signal tmp_11_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal tmp_9_reg_767 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_771 : STD_LOGIC_VECTOR (0 downto 0);
    signal expected_bytes_3_reg_222 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_1_fu_387_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op45_write_state2 : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal packetOut_dest_V_fu_442_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal packetOut_dest_V_reg_761 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_predicate_op74_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op113_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal packetIn_data_V_fu_456_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal packetIn_data_V_reg_775 : STD_LOGIC_VECTOR (63 downto 0);
    signal packetIn_keep_V_reg_780 : STD_LOGIC_VECTOR (7 downto 0);
    signal expected_bytes_4_3_fu_554_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_3_reg_785 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_reg_791 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_796 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_reg_801 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_806 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal expected_bytes_reg_195 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal expected_bytes_2_reg_207 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_expected_bytes_3_phi_fu_226_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_expected_bytes_6_phi_fu_238_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_7_fu_664_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_213_fu_352_p7 : STD_LOGIC_VECTOR (128 downto 0);
    signal tmp_11_1_fu_417_p7 : STD_LOGIC_VECTOR (128 downto 0);
    signal tmp_427_fu_672_p7 : STD_LOGIC_VECTOR (128 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dest_V_fu_142 : STD_LOGIC_VECTOR (15 downto 0);
    signal dest_V_1_fu_391_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_id_V_fu_146 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_246_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_fu_150 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Result_6_fu_369_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Result_4_fu_405_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_dest_V_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_last_V_fu_158 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_1_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_keep_V_fu_162 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_id_V_1_fu_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_fu_170 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Result_s_fu_279_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_256_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_s_53_fu_377_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_271_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_413_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_15_fu_452_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_17_fu_470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal expected_bytes_5_cas_fu_478_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal expected_bytes_4_s_fu_484_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal expected_bytes_4_ca_fu_492_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_496_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal expected_bytes_5_1_fu_504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_1_fu_510_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_518_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal expected_bytes_5_2_fu_526_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_2_fu_532_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_540_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal expected_bytes_5_3_fu_548_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_609_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_5_4_fu_621_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_4_fu_626_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_5_5_fu_632_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_5_fu_638_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_5_6_fu_645_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_4_6_fu_651_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal expected_bytes_5_7_fu_658_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_151 : BOOLEAN;
    signal ap_condition_87 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((tmp_9_fu_446_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    expected_bytes_2_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if (((tmp_3_fu_331_p2 = ap_const_lv1_0) and (tmp_11_fu_325_p2 = ap_const_lv1_0))) then 
                    expected_bytes_2_reg_207 <= expected_bytes_reg_195;
                elsif (((tmp_11_fu_325_p2 = ap_const_lv1_0) and (tmp_3_fu_331_p2 = ap_const_lv1_1))) then 
                    expected_bytes_2_reg_207 <= expected_bytes_1_fu_387_p1;
                elsif ((tmp_11_fu_325_p2 = ap_const_lv1_1)) then 
                    expected_bytes_2_reg_207 <= ap_const_lv32_FFFFFFFF;
                end if;
            end if; 
        end if;
    end process;

    expected_bytes_3_reg_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_9_reg_767 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                expected_bytes_3_reg_222 <= ap_phi_mux_expected_bytes_6_phi_fu_238_p4;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                expected_bytes_3_reg_222 <= expected_bytes_2_reg_207;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if ((tmp_11_fu_325_p2 = ap_const_lv1_1)) then 
                                        p_Val2_s_fu_150(4 downto 0) <= p_Result_4_fu_405_p3(4 downto 0);
                elsif (((tmp_11_fu_325_p2 = ap_const_lv1_0) and (tmp_3_fu_331_p2 = ap_const_lv1_1))) then 
                                        p_Val2_s_fu_150(4 downto 0) <= p_Result_6_fu_369_p3(4 downto 0);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (tmp_11_fu_325_p2 = ap_const_lv1_0) and (tmp_3_fu_331_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                dest_V_fu_142 <= dest_V_1_fu_391_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op74_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                expected_bytes_4_3_reg_785 <= expected_bytes_4_3_fu_554_p3;
                packetIn_data_V_reg_775 <= packetIn_data_V_fu_456_p1;
                packetIn_keep_V_reg_780 <= stream_in_V_dout(79 downto 72);
                tmp_21_reg_791 <= stream_in_V_dout(76 downto 76);
                tmp_22_reg_796 <= stream_in_V_dout(77 downto 77);
                tmp_23_reg_801 <= stream_in_V_dout(78 downto 78);
                tmp_24_reg_806 <= stream_in_V_dout(79 downto 79);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                expected_bytes_reg_195 <= expected_bytes_3_reg_222;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                packetOut_dest_V_reg_761 <= packetOut_dest_V_fu_442_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_9_fu_446_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_2_reg_771 <= (0=>stream_in_V_empty_n, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_9_reg_767 <= tmp_9_fu_446_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op74_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_dest_V_fu_154 <= packetOut_dest_V_reg_761;
                tmp_keep_V_fu_162 <= stream_in_V_dout(79 downto 72);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op113_write_state5 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_id_V_1_fu_166 <= tmp_id_V_fu_146;
                tmp_last_V_fu_158 <= tmp_last_V_1_fu_615_p2;
                    tmp_user_V_fu_170(4 downto 0) <= p_Val2_s_fu_150(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (tmp_11_fu_325_p2 = ap_const_lv1_0) and (tmp_3_fu_331_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (tmp_11_fu_325_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then
                tmp_id_V_fu_146 <= stream_in_V_dout(23 downto 16);
            end if;
        end if;
    end process;
    p_Val2_s_fu_150(39 downto 5) <= "00000000000000000000000000000000000";
    tmp_user_V_fu_170(39 downto 5) <= "00000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (stream_in_V_empty_n, stream_out_V_full_n, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, tmp_11_fu_325_p2, ap_enable_reg_pp0_iter1, ap_predicate_op45_write_state2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if ((not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_predicate_op74_read_state4, ap_predicate_op113_write_state5)
    begin
                ap_block_pp0_stage0_01001 <= (((stream_out_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op113_write_state5 = ap_const_boolean_1)) or ((stream_in_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op74_read_state4 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_predicate_op74_read_state4, ap_predicate_op113_write_state5)
    begin
                ap_block_pp0_stage0_11001 <= (((stream_out_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op113_write_state5 = ap_const_boolean_1)) or ((stream_in_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op74_read_state4 = ap_const_boolean_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_predicate_op74_read_state4, ap_predicate_op113_write_state5)
    begin
                ap_block_pp0_stage0_subdone <= (((stream_out_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_predicate_op113_write_state5 = ap_const_boolean_1)) or ((stream_in_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op74_read_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state2_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, tmp_11_fu_325_p2, ap_predicate_op45_write_state2)
    begin
                ap_block_state2 <= ((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)));
    end process;


    ap_block_state4_pp0_stage0_iter0_assign_proc : process(stream_in_V_empty_n, ap_predicate_op74_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter0 <= ((stream_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op74_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage0_iter1_assign_proc : process(stream_out_V_full_n, ap_predicate_op113_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op113_write_state5 = ap_const_boolean_1));
    end process;


    ap_condition_151_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_9_reg_767)
    begin
                ap_condition_151 <= ((tmp_9_reg_767 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_87_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_CS_fsm_state2, tmp_11_fu_325_p2, ap_predicate_op45_write_state2)
    begin
                ap_condition_87 <= (not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_expected_bytes_3_phi_fu_226_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_9_reg_767, expected_bytes_3_reg_222, ap_phi_mux_expected_bytes_6_phi_fu_238_p4)
    begin
        if (((tmp_9_reg_767 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_expected_bytes_3_phi_fu_226_p4 <= ap_phi_mux_expected_bytes_6_phi_fu_238_p4;
        else 
            ap_phi_mux_expected_bytes_3_phi_fu_226_p4 <= expected_bytes_3_reg_222;
        end if; 
    end process;


    ap_phi_mux_expected_bytes_6_phi_fu_238_p4_assign_proc : process(tmp_2_reg_771, expected_bytes_3_reg_222, expected_bytes_4_7_fu_664_p3, ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234, ap_condition_151)
    begin
        if ((ap_const_boolean_1 = ap_condition_151)) then
            if ((tmp_2_reg_771 = ap_const_lv1_0)) then 
                ap_phi_mux_expected_bytes_6_phi_fu_238_p4 <= expected_bytes_3_reg_222;
            elsif ((tmp_2_reg_771 = ap_const_lv1_1)) then 
                ap_phi_mux_expected_bytes_6_phi_fu_238_p4 <= expected_bytes_4_7_fu_664_p3;
            else 
                ap_phi_mux_expected_bytes_6_phi_fu_238_p4 <= ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234;
            end if;
        else 
            ap_phi_mux_expected_bytes_6_phi_fu_238_p4 <= ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234;
        end if; 
    end process;

    ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op113_write_state5_assign_proc : process(tmp_9_reg_767, tmp_2_reg_771)
    begin
                ap_predicate_op113_write_state5 <= ((tmp_2_reg_771 = ap_const_lv1_1) and (tmp_9_reg_767 = ap_const_lv1_1));
    end process;


    ap_predicate_op45_write_state2_assign_proc : process(tmp_11_fu_325_p2, tmp_3_fu_331_p2)
    begin
                ap_predicate_op45_write_state2 <= ((tmp_3_fu_331_p2 = ap_const_lv1_0) and (tmp_11_fu_325_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op74_read_state4_assign_proc : process(tmp_9_fu_446_p2, tmp_2_nbreadreq_fu_187_p3)
    begin
                ap_predicate_op74_read_state4 <= ((tmp_2_nbreadreq_fu_187_p3 = ap_const_lv1_1) and (tmp_9_fu_446_p2 = ap_const_lv1_1));
    end process;

    dest_V_1_fu_391_p1 <= stream_in_V_dout(16 - 1 downto 0);
    expected_bytes_1_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_s_53_fu_377_p4),32));
    expected_bytes_4_1_fu_510_p3 <= 
        expected_bytes_5_1_fu_504_p2 when (tmp_18_fu_496_p3(0) = '1') else 
        expected_bytes_4_ca_fu_492_p1;
    expected_bytes_4_2_fu_532_p3 <= 
        expected_bytes_5_2_fu_526_p2 when (tmp_19_fu_518_p3(0) = '1') else 
        expected_bytes_4_1_fu_510_p3;
    expected_bytes_4_3_fu_554_p3 <= 
        expected_bytes_5_3_fu_548_p2 when (tmp_20_fu_540_p3(0) = '1') else 
        expected_bytes_4_2_fu_532_p3;
    expected_bytes_4_4_fu_626_p3 <= 
        expected_bytes_5_4_fu_621_p2 when (tmp_21_reg_791(0) = '1') else 
        expected_bytes_4_3_reg_785;
    expected_bytes_4_5_fu_638_p3 <= 
        expected_bytes_5_5_fu_632_p2 when (tmp_22_reg_796(0) = '1') else 
        expected_bytes_4_4_fu_626_p3;
    expected_bytes_4_6_fu_651_p3 <= 
        expected_bytes_5_6_fu_645_p2 when (tmp_23_reg_801(0) = '1') else 
        expected_bytes_4_5_fu_638_p3;
    expected_bytes_4_7_fu_664_p3 <= 
        expected_bytes_5_7_fu_658_p2 when (tmp_24_reg_806(0) = '1') else 
        expected_bytes_4_6_fu_651_p3;
    expected_bytes_4_ca_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(expected_bytes_4_s_fu_484_p3),32));
    expected_bytes_4_s_fu_484_p3 <= 
        expected_bytes_5_cas_fu_478_p2 when (tmp_17_fu_470_p3(0) = '1') else 
        tmp_15_fu_452_p1;
    expected_bytes_5_1_fu_504_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_ca_fu_492_p1));
    expected_bytes_5_2_fu_526_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_1_fu_510_p3));
    expected_bytes_5_3_fu_548_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_2_fu_532_p3));
    expected_bytes_5_4_fu_621_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_3_reg_785));
    expected_bytes_5_5_fu_632_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_4_fu_626_p3));
    expected_bytes_5_6_fu_645_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_5_fu_638_p3));
    expected_bytes_5_7_fu_658_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(expected_bytes_4_6_fu_651_p3));
    expected_bytes_5_cas_fu_478_p2 <= std_logic_vector(signed(ap_const_lv31_7FFFFFFF) + signed(tmp_15_fu_452_p1));
    grp_fu_246_p4 <= stream_in_V_dout(23 downto 16);
    grp_fu_256_p4 <= stream_in_V_dout(59 downto 56);
    p_Result_4_fu_405_p3 <= (ap_const_lv36_0 & grp_fu_256_p4);
    p_Result_6_fu_369_p3 <= (ap_const_lv36_1 & grp_fu_256_p4);
    p_Result_s_53_fu_377_p4 <= stream_in_V_dout(47 downto 32);
    p_Result_s_fu_279_p4 <= stream_in_V_dout(31 downto 24);
    packetIn_data_V_fu_456_p1 <= stream_in_V_dout(64 - 1 downto 0);
    packetOut_dest_V_fu_442_p1 <= dest_V_fu_142(8 - 1 downto 0);

    stream_in_V_blk_n_assign_proc : process(stream_in_V_empty_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, tmp_9_fu_446_p2, tmp_2_nbreadreq_fu_187_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((tmp_2_nbreadreq_fu_187_p3 = ap_const_lv1_1) and (tmp_9_fu_446_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            stream_in_V_blk_n <= stream_in_V_empty_n;
        else 
            stream_in_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_V_read_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, tmp_11_fu_325_p2, ap_predicate_op45_write_state2, ap_predicate_op74_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op74_read_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            stream_in_V_read <= ap_const_logic_1;
        else 
            stream_in_V_read <= ap_const_logic_0;
        end if; 
    end process;


    stream_out_V_blk_n_assign_proc : process(stream_out_V_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, tmp_11_fu_325_p2, tmp_3_fu_331_p2, ap_enable_reg_pp0_iter1, tmp_9_reg_767, tmp_2_reg_771)
    begin
        if ((((tmp_2_reg_771 = ap_const_lv1_1) and (tmp_9_reg_767 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_3_fu_331_p2 = ap_const_lv1_0) and (tmp_11_fu_325_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            stream_out_V_blk_n <= stream_out_V_full_n;
        else 
            stream_out_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_out_V_din_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, tmp_11_fu_325_p2, ap_enable_reg_pp0_iter1, ap_predicate_op45_write_state2, ap_predicate_op113_write_state5, tmp_213_fu_352_p7, tmp_11_1_fu_417_p7, tmp_427_fu_672_p7, ap_block_pp0_stage0_01001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op113_write_state5 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            stream_out_V_din <= tmp_427_fu_672_p7;
        elsif ((not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (tmp_11_fu_325_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            stream_out_V_din <= tmp_11_1_fu_417_p7;
        elsif ((not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op45_write_state2 = ap_const_boolean_1))) then 
            stream_out_V_din <= tmp_213_fu_352_p7;
        else 
            stream_out_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_out_V_write_assign_proc : process(stream_in_V_empty_n, stream_out_V_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, tmp_11_fu_325_p2, ap_enable_reg_pp0_iter1, ap_predicate_op45_write_state2, ap_predicate_op113_write_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op113_write_state5 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or (not(((stream_in_V_empty_n = ap_const_logic_0) or ((stream_out_V_full_n = ap_const_logic_0) and (ap_predicate_op45_write_state2 = ap_const_boolean_1)) or ((tmp_11_fu_325_p2 = ap_const_lv1_1) and (stream_out_V_full_n = ap_const_logic_0)))) and (tmp_11_fu_325_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            stream_out_V_write <= ap_const_logic_1;
        else 
            stream_out_V_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_319_p2 <= "1" when (p_Result_s_fu_279_p4 = ap_const_lv8_0) else "0";
    tmp_11_1_fu_417_p7 <= (((((ap_const_lv36_0 & grp_fu_256_p4) & grp_fu_246_p4) & ap_const_lv8_FF) & tmp_fu_271_p3) & tmp_12_fu_413_p1);
    tmp_11_fu_325_p2 <= (tmp_8_fu_313_p2 or tmp_10_fu_319_p2);
    tmp_12_fu_413_p1 <= stream_in_V_dout(72 - 1 downto 0);
    tmp_15_fu_452_p1 <= ap_phi_mux_expected_bytes_3_phi_fu_226_p4(31 - 1 downto 0);
    tmp_17_fu_470_p3 <= stream_in_V_dout(72 downto 72);
    tmp_18_fu_496_p3 <= stream_in_V_dout(73 downto 73);
    tmp_19_fu_518_p3 <= stream_in_V_dout(74 downto 74);
    tmp_20_fu_540_p3 <= stream_in_V_dout(75 downto 75);
    tmp_213_fu_352_p7 <= (((((tmp_user_V_fu_170 & tmp_id_V_1_fu_166) & tmp_keep_V_fu_162) & tmp_last_V_fu_158) & tmp_dest_V_fu_154) & ap_const_lv64_FFFFFFFFFFFFFFFF);
    tmp_2_nbreadreq_fu_187_p3 <= (0=>stream_in_V_empty_n, others=>'-');
    tmp_3_fu_331_p2 <= "1" when (p_Result_s_fu_279_p4 = ap_const_lv8_2) else "0";
    tmp_427_fu_672_p7 <= (((((p_Val2_s_fu_150 & tmp_id_V_fu_146) & packetIn_keep_V_reg_780) & tmp_last_V_1_fu_615_p2) & packetOut_dest_V_reg_761) & packetIn_data_V_reg_775);
    tmp_4_fu_289_p2 <= "1" when (p_Result_s_fu_279_p4 = ap_const_lv8_5) else "0";
    tmp_5_fu_295_p2 <= "1" when (p_Result_s_fu_279_p4 = ap_const_lv8_4) else "0";
    tmp_6_fu_301_p2 <= (tmp_5_fu_295_p2 or tmp_4_fu_289_p2);
    tmp_7_fu_307_p2 <= "1" when (p_Result_s_fu_279_p4 = ap_const_lv8_1) else "0";
    tmp_8_fu_313_p2 <= (tmp_7_fu_307_p2 or tmp_6_fu_301_p2);
    tmp_9_fu_446_p2 <= "1" when (signed(ap_phi_mux_expected_bytes_3_phi_fu_226_p4) > signed(ap_const_lv32_0)) else "0";
    tmp_fu_271_p3 <= stream_in_V_dout(80 downto 80);
    tmp_last_V_1_fu_615_p2 <= "1" when (signed(tmp_s_fu_609_p2) < signed(ap_const_lv32_1)) else "0";
    tmp_s_fu_609_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFF8) + signed(expected_bytes_3_reg_222));
end behav;
