// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ip_handler_check_ip_checksum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        myIpAddress_V,
        ipDataFifo_V_dout,
        ipDataFifo_V_empty_n,
        ipDataFifo_V_read,
        ipDataCheckFifo_V_din,
        ipDataCheckFifo_V_full_n,
        ipDataCheckFifo_V_write,
        iph_subSumsFifoOut_V_din,
        iph_subSumsFifoOut_V_full_n,
        iph_subSumsFifoOut_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv8_2 = 8'b10;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_37 = 32'b110111;
parameter    ap_const_lv8_FE = 8'b11111110;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_const_lv32_47 = 32'b1000111;
parameter    ap_const_lv32_48 = 32'b1001000;
parameter    ap_const_lv32_33 = 32'b110011;
parameter    ap_const_lv32_45 = 32'b1000101;
parameter    ap_const_lv32_46 = 32'b1000110;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] myIpAddress_V;
input  [72:0] ipDataFifo_V_dout;
input   ipDataFifo_V_empty_n;
output   ipDataFifo_V_read;
output  [72:0] ipDataCheckFifo_V_din;
input   ipDataCheckFifo_V_full_n;
output   ipDataCheckFifo_V_write;
output  [68:0] iph_subSumsFifoOut_V_din;
input   iph_subSumsFifoOut_V_full_n;
output   iph_subSumsFifoOut_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ipDataFifo_V_read;
reg[72:0] ipDataCheckFifo_V_din;
reg ipDataCheckFifo_V_write;
reg[68:0] iph_subSumsFifoOut_V_din;
reg iph_subSumsFifoOut_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm = 1'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_20;
reg   [0:0] cics_state = 1'b0;
reg   [63:0] cics_prevWord_data_V = 64'b0000000000000000000000000000000000000000000000000000000000000000;
reg   [7:0] cics_prevWord_keep_V = 8'b00000000;
reg   [2:0] cics_wordCount_V = 3'b000;
reg   [15:0] cics_ip_sums_V_0 = 16'b0000000000000000;
reg   [15:0] cics_ip_sums_V_1 = 16'b0000000000000000;
reg   [15:0] cics_ip_sums_V_2 = 16'b0000000000000000;
reg   [15:0] cics_ip_sums_V_3 = 16'b0000000000000000;
reg   [7:0] cics_ipHeaderLen_V = 8'b00000000;
reg   [31:0] cics_dstIpAddress_V = 32'b00000000000000000000000000000000;
wire   [31:0] p_Result_4_fu_1059_p5;
reg   [31:0] cics_dstIpAddress_V_loc_phi_fu_253_p4;
wire   [0:0] tmp_nbreadreq_fu_206_p3;
wire   [0:0] grp_nbwritereq_fu_214_p3;
wire   [0:0] tmp_7_nbwritereq_fu_222_p3;
wire   [7:0] cics_ipHeaderLen_V_load_load_fu_545_p1;
wire   [0:0] tmp_27_fu_1504_p2;
reg    ap_sig_bdd_117;
wire   [0:0] tmp_s_fu_1049_p2;
reg   [0:0] cics_wordCount_V_flag_phi_fu_262_p16;
reg   [2:0] cics_wordCount_V_load_1_phi_fu_291_p16;
wire   [0:0] tmp_last_V_fu_1532_p2;
wire   [0:0] tmp_28_phi_fu_316_p4;
reg   [0:0] cics_wordCount_V_flag_1_phi_fu_326_p4;
wire   [0:0] currWord_last_V_fu_497_p3;
reg   [2:0] cics_wordCount_V_new_1_phi_fu_337_p4;
wire   [68:0] tmp_2_8_fu_1232_p6;
wire   [68:0] tmp_1_11_fu_1301_p6;
wire   [72:0] tmp_3_2_fu_1539_p6;
wire   [72:0] tmp_4_fu_1590_p4;
wire   [63:0] currWord_data_V_fu_483_p1;
wire   [15:0] tmp_56_fu_621_p2;
wire   [15:0] tmp_39_fu_809_p2;
wire   [15:0] tmp_sum0_V_1_fu_1116_p2;
wire   [15:0] tmp_sum0_V_fu_1285_p2;
wire   [15:0] tmp_74_fu_1354_p2;
wire   [15:0] tmp_60_fu_667_p2;
wire   [15:0] tmp_43_fu_855_p2;
wire   [15:0] tmp_sum1_V_1_fu_1166_p2;
wire   [15:0] tmp_78_fu_1400_p2;
wire   [15:0] tmp_64_fu_713_p2;
wire   [15:0] tmp_47_fu_901_p2;
wire   [15:0] tmp_sum2_V_1_fu_1216_p2;
wire   [15:0] tmp_82_fu_1446_p2;
wire   [15:0] tmp_68_fu_759_p2;
wire   [15:0] tmp_51_fu_947_p2;
wire   [15:0] tmp_30_fu_993_p2;
wire   [15:0] tmp_86_fu_1492_p2;
wire   [7:0] grp_fu_416_p2;
wire   [7:0] p_1_fu_1015_p1;
wire   [31:0] p_Result_s_fu_565_p5;
wire   [0:0] grp_fu_433_p2;
wire   [0:0] grp_fu_439_p2;
wire   [15:0] p_Result_6_fu_555_p4;
wire   [7:0] tmp_52_fu_583_p1;
wire   [7:0] grp_fu_346_p4;
wire   [15:0] p_Result_14_fu_587_p3;
wire   [16:0] extLd_fu_517_p1;
wire   [16:0] tmp_10_fu_595_p1;
wire   [16:0] tmp_11_fu_599_p2;
wire   [0:0] tmp_53_fu_605_p3;
wire   [15:0] tmp_55_fu_617_p1;
wire   [15:0] tmp_54_fu_613_p1;
wire   [7:0] grp_fu_366_p4;
wire   [7:0] grp_fu_356_p4;
wire   [15:0] p_Result_67_1_fu_633_p3;
wire   [16:0] tmp_sum1_V_fu_525_p1;
wire   [16:0] tmp_30_1_fu_641_p1;
wire   [16:0] tmp_31_1_fu_645_p2;
wire   [0:0] tmp_57_fu_651_p3;
wire   [15:0] tmp_59_fu_663_p1;
wire   [15:0] tmp_58_fu_659_p1;
wire   [7:0] grp_fu_386_p4;
wire   [7:0] grp_fu_376_p4;
wire   [15:0] p_Result_67_2_fu_679_p3;
wire   [16:0] tmp_sum2_V_fu_533_p1;
wire   [16:0] tmp_30_2_fu_687_p1;
wire   [16:0] tmp_31_2_fu_691_p2;
wire   [0:0] tmp_61_fu_697_p3;
wire   [15:0] tmp_63_fu_709_p1;
wire   [15:0] tmp_62_fu_705_p1;
wire   [7:0] grp_fu_406_p4;
wire   [7:0] grp_fu_396_p4;
wire   [15:0] p_Result_67_3_fu_725_p3;
wire   [16:0] tmp_sum3_V_fu_541_p1;
wire   [16:0] tmp_30_3_fu_733_p1;
wire   [16:0] tmp_31_3_fu_737_p2;
wire   [0:0] tmp_65_fu_743_p3;
wire   [15:0] tmp_67_fu_755_p1;
wire   [15:0] tmp_66_fu_751_p1;
wire   [7:0] tmp_35_fu_771_p1;
wire   [15:0] p_Result_10_fu_775_p3;
wire   [16:0] tmp_1_fu_783_p1;
wire   [16:0] tmp_2_fu_787_p2;
wire   [0:0] tmp_36_fu_793_p3;
wire   [15:0] tmp_38_fu_805_p1;
wire   [15:0] tmp_37_fu_801_p1;
wire   [15:0] p_Result_62_1_fu_821_p3;
wire   [16:0] tmp_24_1_fu_829_p1;
wire   [16:0] tmp_25_1_fu_833_p2;
wire   [0:0] tmp_40_fu_839_p3;
wire   [15:0] tmp_42_fu_851_p1;
wire   [15:0] tmp_41_fu_847_p1;
wire   [15:0] p_Result_62_2_fu_867_p3;
wire   [16:0] tmp_24_2_fu_875_p1;
wire   [16:0] tmp_25_2_fu_879_p2;
wire   [0:0] tmp_44_fu_885_p3;
wire   [15:0] tmp_46_fu_897_p1;
wire   [15:0] tmp_45_fu_893_p1;
wire   [15:0] p_Result_62_3_fu_913_p3;
wire   [16:0] tmp_24_3_fu_921_p1;
wire   [16:0] tmp_25_3_fu_925_p2;
wire   [0:0] tmp_48_fu_931_p3;
wire   [15:0] tmp_50_fu_943_p1;
wire   [15:0] tmp_49_fu_939_p1;
wire   [15:0] p_Result_22_fu_959_p3;
wire   [16:0] tmp_8_fu_967_p1;
wire   [16:0] tmp_9_fu_971_p2;
wire   [0:0] tmp_19_fu_977_p3;
wire   [15:0] tmp_25_fu_989_p1;
wire   [15:0] tmp_21_fu_985_p1;
wire   [3:0] p_Result_5_fu_1005_p4;
wire   [15:0] tmp_69_fu_1055_p1;
wire   [7:0] tmp_92_fu_1078_p1;
wire   [15:0] p_Result_21_fu_1082_p3;
wire   [16:0] tmp_22_fu_1090_p1;
wire   [16:0] tmp_23_fu_1094_p2;
wire   [0:0] tmp_93_fu_1100_p3;
wire   [15:0] tmp_95_fu_1112_p1;
wire   [15:0] tmp_94_fu_1108_p1;
wire   [15:0] p_Result_76_1_fu_1132_p3;
wire   [16:0] tmp_41_1_fu_1140_p1;
wire   [16:0] tmp_42_1_fu_1144_p2;
wire   [0:0] tmp_97_fu_1150_p3;
wire   [15:0] tmp_99_fu_1162_p1;
wire   [15:0] tmp_98_fu_1158_p1;
wire   [15:0] p_Result_76_2_fu_1182_p3;
wire   [16:0] tmp_41_2_fu_1190_p1;
wire   [16:0] tmp_42_2_fu_1194_p2;
wire   [0:0] tmp_101_fu_1200_p3;
wire   [15:0] tmp_103_fu_1212_p1;
wire   [15:0] tmp_102_fu_1208_p1;
wire   [0:0] grp_fu_445_p2;
wire   [16:0] tmp_sum2_V_1_cast_fu_1222_p1;
wire   [16:0] tmp_sum1_V_1_cast_fu_1172_p1;
wire   [16:0] tmp_sum0_V_1_cast_fu_1122_p1;
wire   [7:0] tmp_87_fu_1247_p1;
wire   [15:0] p_Result_23_fu_1251_p3;
wire   [16:0] tmp_16_fu_1259_p1;
wire   [16:0] tmp_17_fu_1263_p2;
wire   [0:0] tmp_88_fu_1269_p3;
wire   [15:0] tmp_90_fu_1281_p1;
wire   [15:0] tmp_89_fu_1277_p1;
wire   [16:0] tmp_sum0_V_cast_fu_1291_p1;
wire   [7:0] tmp_70_fu_1316_p1;
wire   [15:0] p_Result_18_fu_1320_p3;
wire   [16:0] tmp_13_fu_1328_p1;
wire   [16:0] tmp_14_fu_1332_p2;
wire   [0:0] tmp_71_fu_1338_p3;
wire   [15:0] tmp_73_fu_1350_p1;
wire   [15:0] tmp_72_fu_1346_p1;
wire   [15:0] p_Result_80_1_fu_1366_p3;
wire   [16:0] tmp_36_1_fu_1374_p1;
wire   [16:0] tmp_37_1_fu_1378_p2;
wire   [0:0] tmp_75_fu_1384_p3;
wire   [15:0] tmp_77_fu_1396_p1;
wire   [15:0] tmp_76_fu_1392_p1;
wire   [15:0] p_Result_80_2_fu_1412_p3;
wire   [16:0] tmp_36_2_fu_1420_p1;
wire   [16:0] tmp_37_2_fu_1424_p2;
wire   [0:0] tmp_79_fu_1430_p3;
wire   [15:0] tmp_81_fu_1442_p1;
wire   [15:0] tmp_80_fu_1438_p1;
wire   [15:0] p_Result_80_3_fu_1458_p3;
wire   [16:0] tmp_36_3_fu_1466_p1;
wire   [16:0] tmp_37_3_fu_1470_p2;
wire   [0:0] tmp_83_fu_1476_p3;
wire   [15:0] tmp_85_fu_1488_p1;
wire   [15:0] tmp_84_fu_1484_p1;
wire   [0:0] tmp_106_fu_1524_p3;
wire   [5:0] p_Result_16_fu_1514_p4;
wire   [1:0] grp_fu_460_p4;
wire   [47:0] tmp_105_fu_1510_p1;
wire   [15:0] grp_fu_451_p4;
wire   [63:0] p_Result_24_fu_1578_p5;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_bdd_921;
reg    ap_sig_bdd_212;
reg    ap_sig_bdd_927;
reg    ap_sig_bdd_929;
reg    ap_sig_bdd_931;
reg    ap_sig_bdd_935;
reg    ap_sig_bdd_941;
reg    ap_sig_bdd_938;
reg    ap_sig_bdd_238;
reg    ap_sig_bdd_945;
reg    ap_sig_bdd_820;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_117)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_212) begin
        if (ap_sig_bdd_921) begin
            cics_dstIpAddress_V <= p_Result_4_fu_1059_p5;
        end else if ((cics_wordCount_V == ap_const_lv3_3)) begin
            cics_dstIpAddress_V <= p_Result_s_fu_565_p5;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_2) & ~ap_sig_bdd_117) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_1) & ~ap_sig_bdd_117))) begin
        cics_ipHeaderLen_V <= ap_const_lv8_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_1) & ~ap_sig_bdd_117)) begin
        cics_ipHeaderLen_V <= p_1_fu_1015_p1;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & ~ap_sig_bdd_117 & ~(cics_ipHeaderLen_V == ap_const_lv8_2) & ~(cics_ipHeaderLen_V == ap_const_lv8_1) & ~(ap_const_lv8_0 == cics_ipHeaderLen_V_load_load_fu_545_p1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_3) & ~ap_sig_bdd_117) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_2) & ~ap_sig_bdd_117))) begin
        cics_ipHeaderLen_V <= grp_fu_416_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_212) begin
        if (ap_sig_bdd_935) begin
            cics_ip_sums_V_0 <= tmp_74_fu_1354_p2;
        end else if (ap_sig_bdd_931) begin
            cics_ip_sums_V_0 <= tmp_sum0_V_fu_1285_p2;
        end else if (ap_sig_bdd_929) begin
            cics_ip_sums_V_0 <= tmp_sum0_V_1_fu_1116_p2;
        end else if ((ap_const_lv3_0 == cics_wordCount_V)) begin
            cics_ip_sums_V_0 <= ap_const_lv16_0;
        end else if ((cics_wordCount_V == ap_const_lv3_2)) begin
            cics_ip_sums_V_0 <= tmp_39_fu_809_p2;
        end else if ((cics_wordCount_V == ap_const_lv3_3)) begin
            cics_ip_sums_V_0 <= tmp_56_fu_621_p2;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_212) begin
        if (ap_sig_bdd_935) begin
            cics_ip_sums_V_1 <= tmp_78_fu_1400_p2;
        end else if (ap_sig_bdd_929) begin
            cics_ip_sums_V_1 <= tmp_sum1_V_1_fu_1166_p2;
        end else if ((ap_const_lv3_0 == cics_wordCount_V)) begin
            cics_ip_sums_V_1 <= ap_const_lv16_0;
        end else if ((cics_wordCount_V == ap_const_lv3_2)) begin
            cics_ip_sums_V_1 <= tmp_43_fu_855_p2;
        end else if ((cics_wordCount_V == ap_const_lv3_3)) begin
            cics_ip_sums_V_1 <= tmp_60_fu_667_p2;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_212) begin
        if (ap_sig_bdd_935) begin
            cics_ip_sums_V_2 <= tmp_82_fu_1446_p2;
        end else if (ap_sig_bdd_929) begin
            cics_ip_sums_V_2 <= tmp_sum2_V_1_fu_1216_p2;
        end else if ((ap_const_lv3_0 == cics_wordCount_V)) begin
            cics_ip_sums_V_2 <= ap_const_lv16_0;
        end else if ((cics_wordCount_V == ap_const_lv3_2)) begin
            cics_ip_sums_V_2 <= tmp_47_fu_901_p2;
        end else if ((cics_wordCount_V == ap_const_lv3_3)) begin
            cics_ip_sums_V_2 <= tmp_64_fu_713_p2;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_212) begin
        if (ap_sig_bdd_935) begin
            cics_ip_sums_V_3 <= tmp_86_fu_1492_p2;
        end else if ((ap_const_lv3_0 == cics_wordCount_V)) begin
            cics_ip_sums_V_3 <= ap_const_lv16_0;
        end else if ((cics_wordCount_V == ap_const_lv3_1)) begin
            cics_ip_sums_V_3 <= tmp_30_fu_993_p2;
        end else if ((cics_wordCount_V == ap_const_lv3_2)) begin
            cics_ip_sums_V_3 <= tmp_51_fu_947_p2;
        end else if ((cics_wordCount_V == ap_const_lv3_3)) begin
            cics_ip_sums_V_3 <= tmp_68_fu_759_p2;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_938) begin
        if (~(ap_const_lv1_0 == cics_state)) begin
            cics_state <= ap_const_lv1_0;
        end else if (ap_sig_bdd_941) begin
            cics_state <= ap_const_lv1_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~ap_sig_bdd_117)) begin
        cics_prevWord_data_V <= currWord_data_V_fu_483_p1;
        cics_prevWord_keep_V <= {{ipDataFifo_V_dout[ap_const_lv32_47 : ap_const_lv32_40]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~ap_sig_bdd_117 & ~(ap_const_lv1_0 == cics_wordCount_V_flag_1_phi_fu_326_p4))) begin
        cics_wordCount_V <= cics_wordCount_V_new_1_phi_fu_337_p4;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_117)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_117))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_117)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_117)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_20)
begin
    if (ap_sig_bdd_20) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// cics_dstIpAddress_V_loc_phi_fu_253_p4 assign process. ///
always @ (cics_dstIpAddress_V or p_Result_4_fu_1059_p5 or tmp_s_fu_1049_p2 or ap_sig_bdd_927)
begin
    if (ap_sig_bdd_927) begin
        if ((ap_const_lv1_0 == tmp_s_fu_1049_p2)) begin
            cics_dstIpAddress_V_loc_phi_fu_253_p4 = cics_dstIpAddress_V;
        end else if (~(ap_const_lv1_0 == tmp_s_fu_1049_p2)) begin
            cics_dstIpAddress_V_loc_phi_fu_253_p4 = p_Result_4_fu_1059_p5;
        end else begin
            cics_dstIpAddress_V_loc_phi_fu_253_p4 = 'bx;
        end
    end else begin
        cics_dstIpAddress_V_loc_phi_fu_253_p4 = 'bx;
    end
end

/// cics_wordCount_V_flag_1_phi_fu_326_p4 assign process. ///
always @ (cics_wordCount_V_flag_phi_fu_262_p16 or currWord_last_V_fu_497_p3 or ap_sig_bdd_238)
begin
    if (ap_sig_bdd_238) begin
        if ((ap_const_lv1_0 == currWord_last_V_fu_497_p3)) begin
            cics_wordCount_V_flag_1_phi_fu_326_p4 = cics_wordCount_V_flag_phi_fu_262_p16;
        end else if (~(ap_const_lv1_0 == currWord_last_V_fu_497_p3)) begin
            cics_wordCount_V_flag_1_phi_fu_326_p4 = ap_const_lv1_1;
        end else begin
            cics_wordCount_V_flag_1_phi_fu_326_p4 = 'bx;
        end
    end else begin
        cics_wordCount_V_flag_1_phi_fu_326_p4 = 'bx;
    end
end

/// cics_wordCount_V_flag_phi_fu_262_p16 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or cics_wordCount_V or cics_ipHeaderLen_V or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or cics_ipHeaderLen_V_load_load_fu_545_p1)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_3)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (ap_const_lv3_0 == cics_wordCount_V)))) begin
        cics_wordCount_V_flag_phi_fu_262_p16 = ap_const_lv1_1;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & ~(cics_ipHeaderLen_V == ap_const_lv8_2) & ~(cics_ipHeaderLen_V == ap_const_lv8_1) & ~(ap_const_lv8_0 == cics_ipHeaderLen_V_load_load_fu_545_p1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (ap_const_lv8_0 == cics_ipHeaderLen_V_load_load_fu_545_p1)))) begin
        cics_wordCount_V_flag_phi_fu_262_p16 = ap_const_lv1_0;
    end else begin
        cics_wordCount_V_flag_phi_fu_262_p16 = 'bx;
    end
end

/// cics_wordCount_V_load_1_phi_fu_291_p16 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or cics_wordCount_V or cics_ipHeaderLen_V or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or cics_ipHeaderLen_V_load_load_fu_545_p1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (ap_const_lv3_0 == cics_wordCount_V))) begin
        cics_wordCount_V_load_1_phi_fu_291_p16 = ap_const_lv3_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_1))) begin
        cics_wordCount_V_load_1_phi_fu_291_p16 = ap_const_lv3_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_2))) begin
        cics_wordCount_V_load_1_phi_fu_291_p16 = ap_const_lv3_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (cics_wordCount_V == ap_const_lv3_3))) begin
        cics_wordCount_V_load_1_phi_fu_291_p16 = ap_const_lv3_4;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & ~(cics_ipHeaderLen_V == ap_const_lv8_2) & ~(cics_ipHeaderLen_V == ap_const_lv8_1) & ~(ap_const_lv8_0 == cics_ipHeaderLen_V_load_load_fu_545_p1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (ap_const_lv8_0 == cics_ipHeaderLen_V_load_load_fu_545_p1)))) begin
        cics_wordCount_V_load_1_phi_fu_291_p16 = cics_wordCount_V;
    end else begin
        cics_wordCount_V_load_1_phi_fu_291_p16 = 'bx;
    end
end

/// cics_wordCount_V_new_1_phi_fu_337_p4 assign process. ///
always @ (cics_wordCount_V_load_1_phi_fu_291_p16 or currWord_last_V_fu_497_p3 or ap_sig_bdd_238)
begin
    if (ap_sig_bdd_238) begin
        if ((ap_const_lv1_0 == currWord_last_V_fu_497_p3)) begin
            cics_wordCount_V_new_1_phi_fu_337_p4 = cics_wordCount_V_load_1_phi_fu_291_p16;
        end else if (~(ap_const_lv1_0 == currWord_last_V_fu_497_p3)) begin
            cics_wordCount_V_new_1_phi_fu_337_p4 = ap_const_lv3_0;
        end else begin
            cics_wordCount_V_new_1_phi_fu_337_p4 = 'bx;
        end
    end else begin
        cics_wordCount_V_new_1_phi_fu_337_p4 = 'bx;
    end
end

/// ipDataCheckFifo_V_din assign process. ///
always @ (cics_state or tmp_3_2_fu_1539_p6 or tmp_4_fu_1590_p4 or ap_sig_bdd_938 or ap_sig_bdd_945)
begin
    if (ap_sig_bdd_938) begin
        if (~(ap_const_lv1_0 == cics_state)) begin
            ipDataCheckFifo_V_din = tmp_4_fu_1590_p4;
        end else if (ap_sig_bdd_945) begin
            ipDataCheckFifo_V_din = tmp_3_2_fu_1539_p6;
        end else begin
            ipDataCheckFifo_V_din = 'bx;
        end
    end else begin
        ipDataCheckFifo_V_din = 'bx;
    end
end

/// ipDataCheckFifo_V_write assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or tmp_27_fu_1504_p2 or ap_sig_bdd_117)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(ap_const_lv1_0 == tmp_27_fu_1504_p2) & ~ap_sig_bdd_117) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == cics_state) & ~ap_sig_bdd_117))) begin
        ipDataCheckFifo_V_write = ap_const_logic_1;
    end else begin
        ipDataCheckFifo_V_write = ap_const_logic_0;
    end
end

/// ipDataFifo_V_read assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or ap_sig_bdd_117)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~ap_sig_bdd_117)) begin
        ipDataFifo_V_read = ap_const_logic_1;
    end else begin
        ipDataFifo_V_read = ap_const_logic_0;
    end
end

/// iph_subSumsFifoOut_V_din assign process. ///
always @ (cics_ipHeaderLen_V or tmp_2_8_fu_1232_p6 or tmp_1_11_fu_1301_p6 or ap_sig_bdd_820)
begin
    if (ap_sig_bdd_820) begin
        if ((cics_ipHeaderLen_V == ap_const_lv8_1)) begin
            iph_subSumsFifoOut_V_din = tmp_1_11_fu_1301_p6;
        end else if ((cics_ipHeaderLen_V == ap_const_lv8_2)) begin
            iph_subSumsFifoOut_V_din = tmp_2_8_fu_1232_p6;
        end else begin
            iph_subSumsFifoOut_V_din = 'bx;
        end
    end else begin
        iph_subSumsFifoOut_V_din = 'bx;
    end
end

/// iph_subSumsFifoOut_V_write assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or cics_wordCount_V or cics_ipHeaderLen_V or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or ap_sig_bdd_117)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_2) & ~ap_sig_bdd_117) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_1) & ~ap_sig_bdd_117))) begin
        iph_subSumsFifoOut_V_write = ap_const_logic_1;
    end else begin
        iph_subSumsFifoOut_V_write = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_117)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_117 assign process. ///
always @ (ap_start or ap_done_reg or cics_state or ipDataFifo_V_empty_n or ipDataCheckFifo_V_full_n or iph_subSumsFifoOut_V_full_n or cics_wordCount_V or cics_ipHeaderLen_V or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or tmp_27_fu_1504_p2)
begin
    ap_sig_bdd_117 = (((ipDataFifo_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3)) | ((ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (iph_subSumsFifoOut_V_full_n == ap_const_logic_0) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_2)) | ((ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (iph_subSumsFifoOut_V_full_n == ap_const_logic_0) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_1)) | ((ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & (ipDataCheckFifo_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_27_fu_1504_p2)) | (~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & (ipDataCheckFifo_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == cics_state)) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_20 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_20 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_212 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or ap_sig_bdd_117)
begin
    ap_sig_bdd_212 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~ap_sig_bdd_117);
end

/// ap_sig_bdd_238 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3)
begin
    ap_sig_bdd_238 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3));
end

/// ap_sig_bdd_820 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or cics_wordCount_V or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3 or ap_sig_bdd_117)
begin
    ap_sig_bdd_820 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & ~ap_sig_bdd_117);
end

/// ap_sig_bdd_921 assign process. ///
always @ (cics_wordCount_V or tmp_s_fu_1049_p2)
begin
    ap_sig_bdd_921 = (~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & ~(ap_const_lv1_0 == tmp_s_fu_1049_p2));
end

/// ap_sig_bdd_927 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or cics_state or cics_wordCount_V or tmp_nbreadreq_fu_206_p3 or grp_nbwritereq_fu_214_p3 or tmp_7_nbwritereq_fu_222_p3)
begin
    ap_sig_bdd_927 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & (ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V));
end

/// ap_sig_bdd_929 assign process. ///
always @ (cics_wordCount_V or cics_ipHeaderLen_V)
begin
    ap_sig_bdd_929 = (~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_2));
end

/// ap_sig_bdd_931 assign process. ///
always @ (cics_wordCount_V or cics_ipHeaderLen_V)
begin
    ap_sig_bdd_931 = (~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & (cics_ipHeaderLen_V == ap_const_lv8_1));
end

/// ap_sig_bdd_935 assign process. ///
always @ (cics_wordCount_V or cics_ipHeaderLen_V or cics_ipHeaderLen_V_load_load_fu_545_p1)
begin
    ap_sig_bdd_935 = (~(cics_wordCount_V == ap_const_lv3_3) & ~(cics_wordCount_V == ap_const_lv3_2) & ~(cics_wordCount_V == ap_const_lv3_1) & ~(ap_const_lv3_0 == cics_wordCount_V) & ~(cics_ipHeaderLen_V == ap_const_lv8_2) & ~(cics_ipHeaderLen_V == ap_const_lv8_1) & ~(ap_const_lv8_0 == cics_ipHeaderLen_V_load_load_fu_545_p1));
end

/// ap_sig_bdd_938 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or grp_nbwritereq_fu_214_p3 or ap_sig_bdd_117)
begin
    ap_sig_bdd_938 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_const_lv1_0 == grp_nbwritereq_fu_214_p3) & ~ap_sig_bdd_117);
end

/// ap_sig_bdd_941 assign process. ///
always @ (cics_state or tmp_nbreadreq_fu_206_p3 or tmp_7_nbwritereq_fu_222_p3 or tmp_28_phi_fu_316_p4 or currWord_last_V_fu_497_p3)
begin
    ap_sig_bdd_941 = ((ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(ap_const_lv1_0 == currWord_last_V_fu_497_p3) & (ap_const_lv1_0 == tmp_28_phi_fu_316_p4));
end

/// ap_sig_bdd_945 assign process. ///
always @ (cics_state or tmp_nbreadreq_fu_206_p3 or tmp_7_nbwritereq_fu_222_p3 or tmp_27_fu_1504_p2)
begin
    ap_sig_bdd_945 = ((ap_const_lv1_0 == cics_state) & ~(ap_const_lv1_0 == tmp_nbreadreq_fu_206_p3) & ~(ap_const_lv1_0 == tmp_7_nbwritereq_fu_222_p3) & ~(ap_const_lv1_0 == tmp_27_fu_1504_p2));
end
assign cics_ipHeaderLen_V_load_load_fu_545_p1 = cics_ipHeaderLen_V;
assign currWord_data_V_fu_483_p1 = ipDataFifo_V_dout[63:0];
assign currWord_last_V_fu_497_p3 = ipDataFifo_V_dout[ap_const_lv32_48];
assign extLd_fu_517_p1 = cics_ip_sums_V_0;
assign grp_fu_346_p4 = {{ipDataFifo_V_dout[ap_const_lv32_F : ap_const_lv32_8]}};
assign grp_fu_356_p4 = {{ipDataFifo_V_dout[ap_const_lv32_1F : ap_const_lv32_18]}};
assign grp_fu_366_p4 = {{ipDataFifo_V_dout[ap_const_lv32_17 : ap_const_lv32_10]}};
assign grp_fu_376_p4 = {{ipDataFifo_V_dout[ap_const_lv32_2F : ap_const_lv32_28]}};
assign grp_fu_386_p4 = {{ipDataFifo_V_dout[ap_const_lv32_27 : ap_const_lv32_20]}};
assign grp_fu_396_p4 = {{ipDataFifo_V_dout[ap_const_lv32_3F : ap_const_lv32_38]}};
assign grp_fu_406_p4 = {{ipDataFifo_V_dout[ap_const_lv32_37 : ap_const_lv32_30]}};
assign grp_fu_416_p2 = ($signed(ap_const_lv8_FE) + $signed(cics_ipHeaderLen_V));
assign grp_fu_433_p2 = (cics_dstIpAddress_V_loc_phi_fu_253_p4 == myIpAddress_V? 1'b1: 1'b0);
assign grp_fu_439_p2 = (cics_dstIpAddress_V_loc_phi_fu_253_p4 == ap_const_lv32_FFFFFFFF? 1'b1: 1'b0);
assign grp_fu_445_p2 = (grp_fu_433_p2 | grp_fu_439_p2);
assign grp_fu_451_p4 = {{cics_prevWord_data_V[ap_const_lv32_3F : ap_const_lv32_30]}};
assign grp_fu_460_p4 = {{cics_prevWord_keep_V[ap_const_lv32_7 : ap_const_lv32_6]}};
assign grp_nbwritereq_fu_214_p3 = ipDataCheckFifo_V_full_n;
assign p_1_fu_1015_p1 = p_Result_5_fu_1005_p4;
assign p_Result_10_fu_775_p3 = {{tmp_35_fu_771_p1}, {grp_fu_346_p4}};
assign p_Result_14_fu_587_p3 = {{tmp_52_fu_583_p1}, {grp_fu_346_p4}};
assign p_Result_16_fu_1514_p4 = {{ipDataFifo_V_dout[ap_const_lv32_45 : ap_const_lv32_40]}};
assign p_Result_18_fu_1320_p3 = {{tmp_70_fu_1316_p1}, {grp_fu_346_p4}};
assign p_Result_21_fu_1082_p3 = {{tmp_92_fu_1078_p1}, {grp_fu_346_p4}};
assign p_Result_22_fu_959_p3 = {{grp_fu_406_p4}, {grp_fu_396_p4}};
assign p_Result_23_fu_1251_p3 = {{tmp_87_fu_1247_p1}, {grp_fu_346_p4}};
assign p_Result_24_fu_1578_p5 = {{ap_const_lv64_0[32'd63 : 32'd16]}, {grp_fu_451_p4}};
assign p_Result_4_fu_1059_p5 = {{tmp_69_fu_1055_p1}, {cics_dstIpAddress_V[32'd15 : 32'd0]}};
assign p_Result_5_fu_1005_p4 = {{ipDataFifo_V_dout[ap_const_lv32_33 : ap_const_lv32_30]}};
assign p_Result_62_1_fu_821_p3 = {{grp_fu_366_p4}, {grp_fu_356_p4}};
assign p_Result_62_2_fu_867_p3 = {{grp_fu_386_p4}, {grp_fu_376_p4}};
assign p_Result_62_3_fu_913_p3 = {{grp_fu_406_p4}, {grp_fu_396_p4}};
assign p_Result_67_1_fu_633_p3 = {{grp_fu_366_p4}, {grp_fu_356_p4}};
assign p_Result_67_2_fu_679_p3 = {{grp_fu_386_p4}, {grp_fu_376_p4}};
assign p_Result_67_3_fu_725_p3 = {{grp_fu_406_p4}, {grp_fu_396_p4}};
assign p_Result_6_fu_555_p4 = {{ipDataFifo_V_dout[ap_const_lv32_3F : ap_const_lv32_30]}};
assign p_Result_76_1_fu_1132_p3 = {{grp_fu_366_p4}, {grp_fu_356_p4}};
assign p_Result_76_2_fu_1182_p3 = {{grp_fu_386_p4}, {grp_fu_376_p4}};
assign p_Result_80_1_fu_1366_p3 = {{grp_fu_366_p4}, {grp_fu_356_p4}};
assign p_Result_80_2_fu_1412_p3 = {{grp_fu_386_p4}, {grp_fu_376_p4}};
assign p_Result_80_3_fu_1458_p3 = {{grp_fu_406_p4}, {grp_fu_396_p4}};
assign p_Result_s_fu_565_p5 = {{cics_dstIpAddress_V[32'd31 : 32'd16]}, {p_Result_6_fu_555_p4}};
assign tmp_101_fu_1200_p3 = tmp_42_2_fu_1194_p2[ap_const_lv32_10];
assign tmp_102_fu_1208_p1 = tmp_42_2_fu_1194_p2[15:0];
assign tmp_103_fu_1212_p1 = tmp_101_fu_1200_p3;
assign tmp_105_fu_1510_p1 = ipDataFifo_V_dout[47:0];
assign tmp_106_fu_1524_p3 = ipDataFifo_V_dout[ap_const_lv32_46];
assign tmp_10_fu_595_p1 = p_Result_14_fu_587_p3;
assign tmp_11_fu_599_p2 = (extLd_fu_517_p1 + tmp_10_fu_595_p1);
assign tmp_13_fu_1328_p1 = p_Result_18_fu_1320_p3;
assign tmp_14_fu_1332_p2 = (extLd_fu_517_p1 + tmp_13_fu_1328_p1);
assign tmp_16_fu_1259_p1 = p_Result_23_fu_1251_p3;
assign tmp_17_fu_1263_p2 = (extLd_fu_517_p1 + tmp_16_fu_1259_p1);
assign tmp_19_fu_977_p3 = tmp_9_fu_971_p2[ap_const_lv32_10];
assign tmp_1_11_fu_1301_p6 = {{{{{grp_fu_445_p2}, {tmp_sum3_V_fu_541_p1}}, {tmp_sum2_V_fu_533_p1}}, {tmp_sum1_V_fu_525_p1}}, {tmp_sum0_V_cast_fu_1291_p1}};
assign tmp_1_fu_783_p1 = p_Result_10_fu_775_p3;
assign tmp_21_fu_985_p1 = tmp_9_fu_971_p2[15:0];
assign tmp_22_fu_1090_p1 = p_Result_21_fu_1082_p3;
assign tmp_23_fu_1094_p2 = (extLd_fu_517_p1 + tmp_22_fu_1090_p1);
assign tmp_24_1_fu_829_p1 = p_Result_62_1_fu_821_p3;
assign tmp_24_2_fu_875_p1 = p_Result_62_2_fu_867_p3;
assign tmp_24_3_fu_921_p1 = p_Result_62_3_fu_913_p3;
assign tmp_25_1_fu_833_p2 = (tmp_sum1_V_fu_525_p1 + tmp_24_1_fu_829_p1);
assign tmp_25_2_fu_879_p2 = (tmp_sum2_V_fu_533_p1 + tmp_24_2_fu_875_p1);
assign tmp_25_3_fu_925_p2 = (tmp_sum3_V_fu_541_p1 + tmp_24_3_fu_921_p1);
assign tmp_25_fu_989_p1 = tmp_19_fu_977_p3;
assign tmp_27_fu_1504_p2 = (cics_wordCount_V_load_1_phi_fu_291_p16 > ap_const_lv3_2? 1'b1: 1'b0);
assign tmp_28_phi_fu_316_p4 = tmp_last_V_fu_1532_p2;
assign tmp_2_8_fu_1232_p6 = {{{{{grp_fu_445_p2}, {tmp_sum3_V_fu_541_p1}}, {tmp_sum2_V_1_cast_fu_1222_p1}}, {tmp_sum1_V_1_cast_fu_1172_p1}}, {tmp_sum0_V_1_cast_fu_1122_p1}};
assign tmp_2_fu_787_p2 = (extLd_fu_517_p1 + tmp_1_fu_783_p1);
assign tmp_30_1_fu_641_p1 = p_Result_67_1_fu_633_p3;
assign tmp_30_2_fu_687_p1 = p_Result_67_2_fu_679_p3;
assign tmp_30_3_fu_733_p1 = p_Result_67_3_fu_725_p3;
assign tmp_30_fu_993_p2 = (tmp_25_fu_989_p1 + tmp_21_fu_985_p1);
assign tmp_31_1_fu_645_p2 = (tmp_sum1_V_fu_525_p1 + tmp_30_1_fu_641_p1);
assign tmp_31_2_fu_691_p2 = (tmp_sum2_V_fu_533_p1 + tmp_30_2_fu_687_p1);
assign tmp_31_3_fu_737_p2 = (tmp_sum3_V_fu_541_p1 + tmp_30_3_fu_733_p1);
assign tmp_35_fu_771_p1 = ipDataFifo_V_dout[7:0];
assign tmp_36_1_fu_1374_p1 = p_Result_80_1_fu_1366_p3;
assign tmp_36_2_fu_1420_p1 = p_Result_80_2_fu_1412_p3;
assign tmp_36_3_fu_1466_p1 = p_Result_80_3_fu_1458_p3;
assign tmp_36_fu_793_p3 = tmp_2_fu_787_p2[ap_const_lv32_10];
assign tmp_37_1_fu_1378_p2 = (tmp_sum1_V_fu_525_p1 + tmp_36_1_fu_1374_p1);
assign tmp_37_2_fu_1424_p2 = (tmp_sum2_V_fu_533_p1 + tmp_36_2_fu_1420_p1);
assign tmp_37_3_fu_1470_p2 = (tmp_sum3_V_fu_541_p1 + tmp_36_3_fu_1466_p1);
assign tmp_37_fu_801_p1 = tmp_2_fu_787_p2[15:0];
assign tmp_38_fu_805_p1 = tmp_36_fu_793_p3;
assign tmp_39_fu_809_p2 = (tmp_38_fu_805_p1 + tmp_37_fu_801_p1);
assign tmp_3_2_fu_1539_p6 = {{{{{tmp_last_V_fu_1532_p2}, {p_Result_16_fu_1514_p4}}, {grp_fu_460_p4}}, {tmp_105_fu_1510_p1}}, {grp_fu_451_p4}};
assign tmp_40_fu_839_p3 = tmp_25_1_fu_833_p2[ap_const_lv32_10];
assign tmp_41_1_fu_1140_p1 = p_Result_76_1_fu_1132_p3;
assign tmp_41_2_fu_1190_p1 = p_Result_76_2_fu_1182_p3;
assign tmp_41_fu_847_p1 = tmp_25_1_fu_833_p2[15:0];
assign tmp_42_1_fu_1144_p2 = (tmp_sum1_V_fu_525_p1 + tmp_41_1_fu_1140_p1);
assign tmp_42_2_fu_1194_p2 = (tmp_sum2_V_fu_533_p1 + tmp_41_2_fu_1190_p1);
assign tmp_42_fu_851_p1 = tmp_40_fu_839_p3;
assign tmp_43_fu_855_p2 = (tmp_42_fu_851_p1 + tmp_41_fu_847_p1);
assign tmp_44_fu_885_p3 = tmp_25_2_fu_879_p2[ap_const_lv32_10];
assign tmp_45_fu_893_p1 = tmp_25_2_fu_879_p2[15:0];
assign tmp_46_fu_897_p1 = tmp_44_fu_885_p3;
assign tmp_47_fu_901_p2 = (tmp_46_fu_897_p1 + tmp_45_fu_893_p1);
assign tmp_48_fu_931_p3 = tmp_25_3_fu_925_p2[ap_const_lv32_10];
assign tmp_49_fu_939_p1 = tmp_25_3_fu_925_p2[15:0];
assign tmp_4_fu_1590_p4 = {{{{ap_const_lv7_40}, {grp_fu_460_p4}}}, {p_Result_24_fu_1578_p5}};
assign tmp_50_fu_943_p1 = tmp_48_fu_931_p3;
assign tmp_51_fu_947_p2 = (tmp_50_fu_943_p1 + tmp_49_fu_939_p1);
assign tmp_52_fu_583_p1 = ipDataFifo_V_dout[7:0];
assign tmp_53_fu_605_p3 = tmp_11_fu_599_p2[ap_const_lv32_10];
assign tmp_54_fu_613_p1 = tmp_11_fu_599_p2[15:0];
assign tmp_55_fu_617_p1 = tmp_53_fu_605_p3;
assign tmp_56_fu_621_p2 = (tmp_55_fu_617_p1 + tmp_54_fu_613_p1);
assign tmp_57_fu_651_p3 = tmp_31_1_fu_645_p2[ap_const_lv32_10];
assign tmp_58_fu_659_p1 = tmp_31_1_fu_645_p2[15:0];
assign tmp_59_fu_663_p1 = tmp_57_fu_651_p3;
assign tmp_60_fu_667_p2 = (tmp_59_fu_663_p1 + tmp_58_fu_659_p1);
assign tmp_61_fu_697_p3 = tmp_31_2_fu_691_p2[ap_const_lv32_10];
assign tmp_62_fu_705_p1 = tmp_31_2_fu_691_p2[15:0];
assign tmp_63_fu_709_p1 = tmp_61_fu_697_p3;
assign tmp_64_fu_713_p2 = (tmp_63_fu_709_p1 + tmp_62_fu_705_p1);
assign tmp_65_fu_743_p3 = tmp_31_3_fu_737_p2[ap_const_lv32_10];
assign tmp_66_fu_751_p1 = tmp_31_3_fu_737_p2[15:0];
assign tmp_67_fu_755_p1 = tmp_65_fu_743_p3;
assign tmp_68_fu_759_p2 = (tmp_67_fu_755_p1 + tmp_66_fu_751_p1);
assign tmp_69_fu_1055_p1 = ipDataFifo_V_dout[15:0];
assign tmp_70_fu_1316_p1 = ipDataFifo_V_dout[7:0];
assign tmp_71_fu_1338_p3 = tmp_14_fu_1332_p2[ap_const_lv32_10];
assign tmp_72_fu_1346_p1 = tmp_14_fu_1332_p2[15:0];
assign tmp_73_fu_1350_p1 = tmp_71_fu_1338_p3;
assign tmp_74_fu_1354_p2 = (tmp_73_fu_1350_p1 + tmp_72_fu_1346_p1);
assign tmp_75_fu_1384_p3 = tmp_37_1_fu_1378_p2[ap_const_lv32_10];
assign tmp_76_fu_1392_p1 = tmp_37_1_fu_1378_p2[15:0];
assign tmp_77_fu_1396_p1 = tmp_75_fu_1384_p3;
assign tmp_78_fu_1400_p2 = (tmp_77_fu_1396_p1 + tmp_76_fu_1392_p1);
assign tmp_79_fu_1430_p3 = tmp_37_2_fu_1424_p2[ap_const_lv32_10];
assign tmp_7_nbwritereq_fu_222_p3 = iph_subSumsFifoOut_V_full_n;
assign tmp_80_fu_1438_p1 = tmp_37_2_fu_1424_p2[15:0];
assign tmp_81_fu_1442_p1 = tmp_79_fu_1430_p3;
assign tmp_82_fu_1446_p2 = (tmp_81_fu_1442_p1 + tmp_80_fu_1438_p1);
assign tmp_83_fu_1476_p3 = tmp_37_3_fu_1470_p2[ap_const_lv32_10];
assign tmp_84_fu_1484_p1 = tmp_37_3_fu_1470_p2[15:0];
assign tmp_85_fu_1488_p1 = tmp_83_fu_1476_p3;
assign tmp_86_fu_1492_p2 = (tmp_85_fu_1488_p1 + tmp_84_fu_1484_p1);
assign tmp_87_fu_1247_p1 = ipDataFifo_V_dout[7:0];
assign tmp_88_fu_1269_p3 = tmp_17_fu_1263_p2[ap_const_lv32_10];
assign tmp_89_fu_1277_p1 = tmp_17_fu_1263_p2[15:0];
assign tmp_8_fu_967_p1 = p_Result_22_fu_959_p3;
assign tmp_90_fu_1281_p1 = tmp_88_fu_1269_p3;
assign tmp_92_fu_1078_p1 = ipDataFifo_V_dout[7:0];
assign tmp_93_fu_1100_p3 = tmp_23_fu_1094_p2[ap_const_lv32_10];
assign tmp_94_fu_1108_p1 = tmp_23_fu_1094_p2[15:0];
assign tmp_95_fu_1112_p1 = tmp_93_fu_1100_p3;
assign tmp_97_fu_1150_p3 = tmp_42_1_fu_1144_p2[ap_const_lv32_10];
assign tmp_98_fu_1158_p1 = tmp_42_1_fu_1144_p2[15:0];
assign tmp_99_fu_1162_p1 = tmp_97_fu_1150_p3;
assign tmp_9_fu_971_p2 = (tmp_sum3_V_fu_541_p1 + tmp_8_fu_967_p1);
assign tmp_last_V_fu_1532_p2 = (tmp_106_fu_1524_p3 ^ ap_const_lv1_1);
assign tmp_nbreadreq_fu_206_p3 = ipDataFifo_V_empty_n;
assign tmp_s_fu_1049_p2 = (cics_wordCount_V == ap_const_lv3_4? 1'b1: 1'b0);
assign tmp_sum0_V_1_cast_fu_1122_p1 = tmp_sum0_V_1_fu_1116_p2;
assign tmp_sum0_V_1_fu_1116_p2 = (tmp_95_fu_1112_p1 + tmp_94_fu_1108_p1);
assign tmp_sum0_V_cast_fu_1291_p1 = tmp_sum0_V_fu_1285_p2;
assign tmp_sum0_V_fu_1285_p2 = (tmp_90_fu_1281_p1 + tmp_89_fu_1277_p1);
assign tmp_sum1_V_1_cast_fu_1172_p1 = tmp_sum1_V_1_fu_1166_p2;
assign tmp_sum1_V_1_fu_1166_p2 = (tmp_99_fu_1162_p1 + tmp_98_fu_1158_p1);
assign tmp_sum1_V_fu_525_p1 = cics_ip_sums_V_1;
assign tmp_sum2_V_1_cast_fu_1222_p1 = tmp_sum2_V_1_fu_1216_p2;
assign tmp_sum2_V_1_fu_1216_p2 = (tmp_103_fu_1212_p1 + tmp_102_fu_1208_p1);
assign tmp_sum2_V_fu_533_p1 = cics_ip_sums_V_2;
assign tmp_sum3_V_fu_541_p1 = cics_ip_sums_V_3;


endmodule //ip_handler_check_ip_checksum

