#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("mem_req_din", 1, hls_out, 0, "ap_bus", "fifo_data", 1),
	Port_Property("mem_req_full_n", 1, hls_in, 0, "ap_bus", "fifo_status", 1),
	Port_Property("mem_req_write", 1, hls_out, 0, "ap_bus", "fifo_update", 1),
	Port_Property("mem_rsp_empty_n", 1, hls_in, 0, "ap_bus", "fifo_status", 1),
	Port_Property("mem_rsp_read", 1, hls_out, 0, "ap_bus", "fifo_update", 1),
	Port_Property("mem_address", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("mem_datain", 32, hls_in, 0, "ap_bus", "unknown", 1),
	Port_Property("mem_dataout", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("mem_size", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("darius_driver_req_din", 1, hls_out, 1, "ap_bus", "fifo_data", 1),
	Port_Property("darius_driver_req_full_n", 1, hls_in, 1, "ap_bus", "fifo_status", 1),
	Port_Property("darius_driver_req_write", 1, hls_out, 1, "ap_bus", "fifo_update", 1),
	Port_Property("darius_driver_rsp_empty_n", 1, hls_in, 1, "ap_bus", "fifo_status", 1),
	Port_Property("darius_driver_rsp_read", 1, hls_out, 1, "ap_bus", "fifo_update", 1),
	Port_Property("darius_driver_address", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("darius_driver_datain", 32, hls_in, 1, "ap_bus", "unknown", 1),
	Port_Property("darius_driver_dataout", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("darius_driver_size", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("id_in_V", 16, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("stream_in_V_dout", 129, hls_in, 3, "ap_fifo", "fifo_data", 6),
	Port_Property("stream_in_V_empty_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 6),
	Port_Property("stream_in_V_read", 1, hls_out, 3, "ap_fifo", "fifo_update", 6),
	Port_Property("stream_out_V_din", 129, hls_out, 4, "ap_fifo", "fifo_data", 6),
	Port_Property("stream_out_V_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 6),
	Port_Property("stream_out_V_write", 1, hls_out, 4, "ap_fifo", "fifo_update", 6),
};
const char* HLS_Design_Meta::dut_name = "dariusController";
