// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _NFR_HH_
#define _NFR_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct NFR : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<81> > stream_in_V_dout;
    sc_in< sc_logic > stream_in_V_empty_n;
    sc_out< sc_logic > stream_in_V_read;
    sc_out< sc_lv<129> > stream_out_V_din;
    sc_in< sc_logic > stream_out_V_full_n;
    sc_out< sc_logic > stream_out_V_write;


    // Module declarations
    NFR(sc_module_name name);
    SC_HAS_PROCESS(NFR);

    ~NFR();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > stream_in_V_blk_n;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > tmp_9_fu_446_p2;
    sc_signal< sc_lv<1> > tmp_2_nbreadreq_fu_187_p3;
    sc_signal< sc_logic > stream_out_V_blk_n;
    sc_signal< sc_lv<1> > tmp_11_fu_325_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_331_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > tmp_9_reg_767;
    sc_signal< sc_lv<1> > tmp_2_reg_771;
    sc_signal< sc_lv<32> > expected_bytes_3_reg_222;
    sc_signal< sc_lv<32> > expected_bytes_1_fu_387_p1;
    sc_signal< bool > ap_predicate_op45_write_state2;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<8> > packetOut_dest_V_fu_442_p1;
    sc_signal< sc_lv<8> > packetOut_dest_V_reg_761;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< bool > ap_predicate_op74_read_state4;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter0;
    sc_signal< bool > ap_predicate_op113_write_state5;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<64> > packetIn_data_V_fu_456_p1;
    sc_signal< sc_lv<64> > packetIn_data_V_reg_775;
    sc_signal< sc_lv<8> > packetIn_keep_V_reg_780;
    sc_signal< sc_lv<32> > expected_bytes_4_3_fu_554_p3;
    sc_signal< sc_lv<32> > expected_bytes_4_3_reg_785;
    sc_signal< sc_lv<1> > tmp_21_reg_791;
    sc_signal< sc_lv<1> > tmp_22_reg_796;
    sc_signal< sc_lv<1> > tmp_23_reg_801;
    sc_signal< sc_lv<1> > tmp_24_reg_806;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_lv<32> > expected_bytes_reg_195;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > expected_bytes_2_reg_207;
    sc_signal< sc_lv<32> > ap_phi_mux_expected_bytes_3_phi_fu_226_p4;
    sc_signal< sc_lv<32> > ap_phi_mux_expected_bytes_6_phi_fu_238_p4;
    sc_signal< sc_lv<32> > expected_bytes_4_7_fu_664_p3;
    sc_signal< sc_lv<32> > ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234;
    sc_signal< sc_lv<129> > tmp_213_fu_352_p7;
    sc_signal< sc_lv<129> > tmp_11_1_fu_417_p7;
    sc_signal< sc_lv<129> > tmp_427_fu_672_p7;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<16> > dest_V_fu_142;
    sc_signal< sc_lv<16> > dest_V_1_fu_391_p1;
    sc_signal< sc_lv<8> > tmp_id_V_fu_146;
    sc_signal< sc_lv<8> > grp_fu_246_p4;
    sc_signal< sc_lv<40> > p_Val2_s_fu_150;
    sc_signal< sc_lv<40> > p_Result_6_fu_369_p3;
    sc_signal< sc_lv<40> > p_Result_4_fu_405_p3;
    sc_signal< sc_lv<8> > tmp_dest_V_fu_154;
    sc_signal< sc_lv<1> > tmp_last_V_fu_158;
    sc_signal< sc_lv<1> > tmp_last_V_1_fu_615_p2;
    sc_signal< sc_lv<8> > tmp_keep_V_fu_162;
    sc_signal< sc_lv<8> > tmp_id_V_1_fu_166;
    sc_signal< sc_lv<40> > tmp_user_V_fu_170;
    sc_signal< sc_lv<8> > p_Result_s_fu_279_p4;
    sc_signal< sc_lv<1> > tmp_5_fu_295_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_289_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_307_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_301_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_319_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_313_p2;
    sc_signal< sc_lv<4> > grp_fu_256_p4;
    sc_signal< sc_lv<16> > p_Result_s_53_fu_377_p4;
    sc_signal< sc_lv<1> > tmp_fu_271_p3;
    sc_signal< sc_lv<72> > tmp_12_fu_413_p1;
    sc_signal< sc_lv<31> > tmp_15_fu_452_p1;
    sc_signal< sc_lv<1> > tmp_17_fu_470_p3;
    sc_signal< sc_lv<31> > expected_bytes_5_cas_fu_478_p2;
    sc_signal< sc_lv<31> > expected_bytes_4_s_fu_484_p3;
    sc_signal< sc_lv<32> > expected_bytes_4_ca_fu_492_p1;
    sc_signal< sc_lv<1> > tmp_18_fu_496_p3;
    sc_signal< sc_lv<32> > expected_bytes_5_1_fu_504_p2;
    sc_signal< sc_lv<32> > expected_bytes_4_1_fu_510_p3;
    sc_signal< sc_lv<1> > tmp_19_fu_518_p3;
    sc_signal< sc_lv<32> > expected_bytes_5_2_fu_526_p2;
    sc_signal< sc_lv<32> > expected_bytes_4_2_fu_532_p3;
    sc_signal< sc_lv<1> > tmp_20_fu_540_p3;
    sc_signal< sc_lv<32> > expected_bytes_5_3_fu_548_p2;
    sc_signal< sc_lv<32> > tmp_s_fu_609_p2;
    sc_signal< sc_lv<32> > expected_bytes_5_4_fu_621_p2;
    sc_signal< sc_lv<32> > expected_bytes_4_4_fu_626_p3;
    sc_signal< sc_lv<32> > expected_bytes_5_5_fu_632_p2;
    sc_signal< sc_lv<32> > expected_bytes_4_5_fu_638_p3;
    sc_signal< sc_lv<32> > expected_bytes_5_6_fu_645_p2;
    sc_signal< sc_lv<32> > expected_bytes_4_6_fu_651_p3;
    sc_signal< sc_lv<32> > expected_bytes_5_7_fu_658_p2;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< bool > ap_condition_151;
    sc_signal< bool > ap_condition_87;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_pp0_stage0;
    static const sc_lv<5> ap_ST_fsm_state6;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_38;
    static const sc_lv<32> ap_const_lv32_3B;
    static const sc_lv<32> ap_const_lv32_50;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<8> ap_const_lv8_5;
    static const sc_lv<8> ap_const_lv8_4;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<8> ap_const_lv8_2;
    static const sc_lv<64> ap_const_lv64_FFFFFFFFFFFFFFFF;
    static const sc_lv<36> ap_const_lv36_1;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<36> ap_const_lv36_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<32> ap_const_lv32_48;
    static const sc_lv<32> ap_const_lv32_4F;
    static const sc_lv<31> ap_const_lv31_7FFFFFFF;
    static const sc_lv<32> ap_const_lv32_49;
    static const sc_lv<32> ap_const_lv32_4A;
    static const sc_lv<32> ap_const_lv32_4B;
    static const sc_lv<32> ap_const_lv32_4C;
    static const sc_lv<32> ap_const_lv32_4D;
    static const sc_lv<32> ap_const_lv32_4E;
    static const sc_lv<32> ap_const_lv32_FFFFFFF8;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state2();
    void thread_ap_block_state4_pp0_stage0_iter0();
    void thread_ap_block_state5_pp0_stage0_iter1();
    void thread_ap_condition_151();
    void thread_ap_condition_87();
    void thread_ap_enable_pp0();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_expected_bytes_3_phi_fu_226_p4();
    void thread_ap_phi_mux_expected_bytes_6_phi_fu_238_p4();
    void thread_ap_phi_reg_pp0_iter1_expected_bytes_6_reg_234();
    void thread_ap_predicate_op113_write_state5();
    void thread_ap_predicate_op45_write_state2();
    void thread_ap_predicate_op74_read_state4();
    void thread_dest_V_1_fu_391_p1();
    void thread_expected_bytes_1_fu_387_p1();
    void thread_expected_bytes_4_1_fu_510_p3();
    void thread_expected_bytes_4_2_fu_532_p3();
    void thread_expected_bytes_4_3_fu_554_p3();
    void thread_expected_bytes_4_4_fu_626_p3();
    void thread_expected_bytes_4_5_fu_638_p3();
    void thread_expected_bytes_4_6_fu_651_p3();
    void thread_expected_bytes_4_7_fu_664_p3();
    void thread_expected_bytes_4_ca_fu_492_p1();
    void thread_expected_bytes_4_s_fu_484_p3();
    void thread_expected_bytes_5_1_fu_504_p2();
    void thread_expected_bytes_5_2_fu_526_p2();
    void thread_expected_bytes_5_3_fu_548_p2();
    void thread_expected_bytes_5_4_fu_621_p2();
    void thread_expected_bytes_5_5_fu_632_p2();
    void thread_expected_bytes_5_6_fu_645_p2();
    void thread_expected_bytes_5_7_fu_658_p2();
    void thread_expected_bytes_5_cas_fu_478_p2();
    void thread_grp_fu_246_p4();
    void thread_grp_fu_256_p4();
    void thread_p_Result_4_fu_405_p3();
    void thread_p_Result_6_fu_369_p3();
    void thread_p_Result_s_53_fu_377_p4();
    void thread_p_Result_s_fu_279_p4();
    void thread_packetIn_data_V_fu_456_p1();
    void thread_packetOut_dest_V_fu_442_p1();
    void thread_stream_in_V_blk_n();
    void thread_stream_in_V_read();
    void thread_stream_out_V_blk_n();
    void thread_stream_out_V_din();
    void thread_stream_out_V_write();
    void thread_tmp_10_fu_319_p2();
    void thread_tmp_11_1_fu_417_p7();
    void thread_tmp_11_fu_325_p2();
    void thread_tmp_12_fu_413_p1();
    void thread_tmp_15_fu_452_p1();
    void thread_tmp_17_fu_470_p3();
    void thread_tmp_18_fu_496_p3();
    void thread_tmp_19_fu_518_p3();
    void thread_tmp_20_fu_540_p3();
    void thread_tmp_213_fu_352_p7();
    void thread_tmp_2_nbreadreq_fu_187_p3();
    void thread_tmp_3_fu_331_p2();
    void thread_tmp_427_fu_672_p7();
    void thread_tmp_4_fu_289_p2();
    void thread_tmp_5_fu_295_p2();
    void thread_tmp_6_fu_301_p2();
    void thread_tmp_7_fu_307_p2();
    void thread_tmp_8_fu_313_p2();
    void thread_tmp_9_fu_446_p2();
    void thread_tmp_fu_271_p3();
    void thread_tmp_last_V_1_fu_615_p2();
    void thread_tmp_s_fu_609_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
