// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of programming
//        bit 31~0 - programming[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of programSafe
//        bit 31~0 - programSafe[31:0] (Read)
// 0x1c : Control signal of programSafe
//        bit 0  - programSafe_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAXISTREAMGATE_AXILITES_ADDR_PROGRAMMING_DATA 0x10
#define XAXISTREAMGATE_AXILITES_BITS_PROGRAMMING_DATA 32
#define XAXISTREAMGATE_AXILITES_ADDR_PROGRAMSAFE_DATA 0x18
#define XAXISTREAMGATE_AXILITES_BITS_PROGRAMSAFE_DATA 32
#define XAXISTREAMGATE_AXILITES_ADDR_PROGRAMSAFE_CTRL 0x1c

